### ISSUE TITLE
Add Atom feeds

### ISSUE THREAD

**Issue by daonb** [hasadna/open-shot#10]
For all the questions, all the answers and for answers for a specific question

**Comment by daonb** [comment]
and a feed for the answers of a specific candidate

**Comment by pwalsh** [comment]
Got feed for all questions.

Got feed of answers for a given question.

Got feed of answers for a given candidate (and a given member).

Need to do a bunch of fixes in the rest of the codebase to make it all work properly :)

**Comment by pwalsh** [comment]
Benny, I have finished this feature, but it is on my seo-101 branch, and I can't do another pull request until you accept my currently waiting one. 

Ping me when you have done the previous one, and I'll open a new pull request for this.

**Comment by daonb** [comment]
Ping!

**Comment by pwalsh** [comment]
Actually, you merged it with the sitemap feature merge. See the commit message on the last commit from me.

Next time, I'll more strictly separate so that feature == my local branch.

**Comment by daonb** [comment]
I've just merged with Yanin and updated to the heroku, take a look. Seems like there are some english strings in the feed that are not in the `po` file...
