### ISSUE TITLE
Choose different city without moving through homepage

### ISSUE THREAD

**Issue by ozomer** [hasadna/open-shot#106]
I'm working on that

**Comment by daonb** [comment]
I've talk to Muson the Design Czar and he suggested we use a map based display to display the question and for the user to select their place. i'm talking to the people of http://opentaba.info/ to see if they'll help us use your interface.

**Comment by gl1000007** [comment]
A map display is a good idea but I suggest to use it in addition to the current localities list, maybe below it on the left sidebar. Also, there is a place to consider adding some infographics, such as number of questions or candidates from each locality.

**Comment by daonb** [comment]
regarding the map & infographics, why not design something?
