### ISSUE TITLE
top bar suggestions

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#111]
I suggest using a constant menu in all pages:
בית, שאלות, מועמדים, אודות
- All links, including "questions" and "candidates", will be visible in every page.
- If no locality has been chosen, "questions" and "candidates" will display country-wide content.
- Candidate sorting ideas: most asked, newest.

**Comment by daonb** [comment]
+1

**Comment by lotan1** [comment]
I suggest somthing that will look more localized
maybe after choosing municipality it should appear as big title
  "עיר לדוגמא"
    "שאלות למועמדים"
then again maybe its not top bar..
