### ISSUE TITLE
cannot register via facebook

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#112]
error:
תצורת היישום אינה מאפשרת את כתובת ה-URL הנתונה.: ‎One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.‎

tried it on firefox, chrome and ie.

**Comment by daonb** [comment]
shit. I forgot to update the urls of the callbacks in facebook and twitter.
will fix soon (on a bus now)
