### ISSUE TITLE
Forgot password? Efes!

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#113]
Maybe it's a tiny detail, but:
When a user forgets their password, he/she sees this message:
!שכחת סיסמה? אפס
There **will be** some users feeling harmed by it.
We can avoid this by changing the sentence to something like:
שכחת סיסמה?  תוכל/י לאפס אותה [כאן](http://oshot.hasadna.org.il/accounts/password/reset/)

Also, in the password reset form, דואל should be replaced with דוא"ל.

**Comment by daonb** [comment]
Good catch. We try to use the plural form so we won't get into the male/female slashes. so it's better to change it to:
שכחתם סיסמה? אפסו

**Comment by gl1000007** [comment]
agreed
