### ISSUE TITLE
add like/share buttons for social networks

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#114]
at least facebook and twitter

**Comment by lotan1** [comment]
the sharing options of כנסת פתוחה pages at the bottom is enough http://oknesset.org/committee/meeting/7694/ 

but check out this manual talkbacks facebook share http://tech.walla.co.il/?w=/4013/2627213

**Comment by gl1000007** [comment]
Yes! כנסת פתוחה is exactly what I mean.
