### ISSUE TITLE
Display a welcome message for virgin places

### ISSUE THREAD

**Issue by daonb** [hasadna/open-shot#116]
Places that still have no questions are the most common pages on the site right now.  Better to display a welcome message calling people to post the first questions to become editors and help us keep it honest and bring the local candidates.

**Comment by tbrisker** [comment]
on it

**Comment by gl1000007** [comment]
הי, הנה כמה הערות ורעיונות
ברשותכם אכתוב את זה בעברית, כדי להימנע מסלט של עברית ואנגלית.
בסוף סיכמתי את כל ההערות לגירסה חדשה של ההודעה, כדי לחסוך לכם העתקות והדבקות.
ההערות הן:
- "אתם בין המשתמשים הראשונים מהרשות". איזו רשות - הרשות הפלסטינית אולי? זו האסוציאציה הראשונה שעלתה לי, ורק אח"כ חשבתי על רשות מקומית. עד כמה שאני מכיר, יש עיריות, ויש רשויות מקומיות. כדי שלא נצטרך לכתוב קוד שיברר אם ביישוב מסוים יש עירייה או רשות מקומית, מציע לשנות ל"אתם בין המשתמשים הראשונים ביישוב זה".
- "ואנחנו זקוקים לעזרתכם" -> "ואנו זקוקים לעזרתכם". שינוי קוסממטי, עניין של טעם. תממשו רק אם אתם חושבים כמוני.
- "כדי לדאוג שהשו"ת המוצגים ברשות יהיו אמינים": לא כל הציבור יודע מה זה שו"ת. מציע לשנות ל"שאלות ותשובות".
  הנוסח המוצע: "כדי לדאוג שהשאלות והתשובות ביישוב זה תהיינה אמינות"
- "עורכים מקומיים" - לקשר לעמוד ה"אודות", לפיסקה הספציפית שעוסקת בתפקיד העורך.
- העלו שאלה - לקשר לדף כתיבת שאלה.

סיכום:
ברוך בואכם. אתם בין המשתמשים הראשונים ביישוב זה ואנו זקוקים לעזרתכם. כדי לדאוג שהשאלות והתשובות ביישוב זה תהיינה אמינות ושהמועמדים ירשמו לאתר ויענו על השאלות, אנו זקוקים ל[עורכים מקומיים](about:blank#LocalEditors). אתם יכולים לקרוא עוד על תפקיד העורכים בעמוד ה[אודות](http://oshot.hasadna.org.il/about) ואם אתם מוכנים לעזור, פשוט [העלו שאלה](about:blank). שלושת השואלים הראשונים מכל רשות יהפכו לעורכים.

**Comment by daonb** [comment]
I prefer you'll change it yourself. I've made you a superuser so you can
now access the admin interface - there's an option on the user menu "ממשק
ניהול" there you need to click the "flat blocks" and for there...

2013/8/6 Gilad L notifications@github.com

> הי, הנה כמה הערות ורעיונות
> ברשותכם אכתוב את זה בעברית, כדי להימנע מסלט של עברית ואנגלית.
> בסוף סיכמתי את כל ההערות לגירסה חדשה של ההודעה, כדי לחסוך לכם העתקות
> והדבקות.
> ההערות הן:
> 
>    -
> 
>    "אתם בין המשתמשים הראשונים מהרשות". איזו רשות - הרשות הפלסטינית אולי?
>    זו האסוציאציה הראשונה שעלתה לי, ורק אח"כ חשבתי על רשות מקומית. עד כמה שאני
>    מכיר, יש עיריות, ויש רשויות מקומיות. כדי שלא נצטרך לכתוב קוד שיברר אם
>    ביישוב מסוים יש עירייה או רשות מקומית, מציע לשנות ל"אתם בין המשתמשים
>    הראשונים ביישוב זה".
>    -
> 
>    "ואנחנו זקוקים לעזרתכם" -> "ואנו זקוקים לעזרתכם". שינוי קוסממטי, עניין
>    של טעם. תממשו רק אם אתם חושבים כמוני.
>    -
> 
>    "כדי לדאוג שהשו"ת המוצגים ברשות יהיו אמינים": לא כל הציבור יודע מה זה
>    שו"ת. מציע לשנות ל"שאלות ותשובות".
>    הנוסח המוצע: "כדי לדאוג שהשאלות והתשובות ביישוב זה תהיינה אמינות"
>    -
> 
>    "עורכים מקומיים" - לקשר לעמוד ה"אודות", לפיסקה הספציפית שעוסקת בתפקיד
>    העורך.
>    -
> 
>    העלו שאלה - לקשר לדף כתיבת שאלה.
> 
> סיכום:
> ברוך בואכם. אתם בין המשתמשים הראשונים ביישוב זה ואנו זקוקים לעזרתכם. כדי
> לדאוג שהשאלות והתשובות ביישוב זה תהיינה אמינות ושהמועמדים ירשמו לאתר ויענו
> על השאלות, אנו זקוקים לעורכים מקומיים. אתם יכולים לקרוא עוד על תפקיד
> העורכים בעמוד האודות http://oshot.hasadna.org.il/about ואם אתם מוכנים
> לעזור, פשוט העלו שאלה. שלושת השואלים הראשונים מכל רשות יהפכו לעורכים.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/116#issuecomment-22168370
> .

## 

http://yeda.us/daonb

**Comment by gl1000007** [comment]
Does the system backup older versions of the block, or I should backup it manually?

**Comment by gl1000007** [comment]
sorry, didn't notice the history button.

**Comment by gl1000007** [comment]
Both blocks changed.
