### ISSUE TITLE
in Search Error page, display entered string

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#118]
Despite the error, it provides _some_ informative feedback to the user, Instead of just a laconic message.
Additionally, if some technical error occurs, like getting gibberish input or in an incorrect text encoding, that error will be shown.

**Comment by daonb** [comment]
How do I get to the search error page?

**Comment by gl1000007** [comment]
By searching for any string, including words which do appear in one ore more questions.
For example try to search for גובה, which can be found in a question written by me, URL follows:

http://oshot.hasadna.org.il/%D7%92%D7%9F-%D7%99%D7%91%D7%A0%D7%94/qna/%D7%9E%D7%94-%D7%A2%D7%9E%D7%93%D7%AA%D7%9A-%D7%91%D7%A0%D7%95%D7%A9%D7%90-%D7%91%D7%A0%D7%99%D7%99%D7%94-%D7%9C%D7%92%D7%95%D7%91%D7%94/

**Comment by daonb** [comment]
well, the word in your question is לגובה not גובה. That's one of the
limitations of the simple search engine we're using - it's not very smart
when it comes to hebrew...

On 2 August 2013 12:43, Gilad L notifications@github.com wrote:

> By trying to find any string, including words which do appear in one ore
> more questions.
> For example try to search for גובה, which can be found in a question
> written by me, URL follows:
> 
> http://oshot.hasadna.org.il/%D7%92%D7%9F-%D7%99%D7%91%D7%A0%D7%94/qna/%D7%9E%D7%94-%D7%A2%D7%9E%D7%93%D7%AA%D7%9A-%D7%91%D7%A0%D7%95%D7%A9%D7%90-%D7%91%D7%A0%D7%99%D7%99%D7%94-%D7%9C%D7%92%D7%95%D7%91%D7%94/
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/118#issuecomment-21996048
> .

## 

http://yeda.us/daonb

**Comment by gl1000007** [comment]
Now I see when I search for לגובה, it shows me the question.
Maybe a separate issue should be opened about this?

also,
There is still a place to reflect the users what they have searched.
Think about this: If you perform a search with no results, all you see is the "no matches found" message. You search for a different string, still no results, and you keep seeing the very same message. Then you may think the site is unresponsive and maybe haven't perform your 2nd search. When the search string is shown, every time you change your search, the page gets updated no matter if results exist or not.
