### ISSUE TITLE
Suuport city council candidates

### ISSUE THREAD

**Issue by daonb** [hasadna/open-shot#126]
Allow candidates to the city council to join, naming their party and displaying their answer alongside the answer from the mayor candidate

**Comment by lotan1** [comment]
Maybe the candidates page can include parties as well, 
candidates to the city council should registerd then as a head of party.
Their answers then can be alongside or even below,
but only for mayor candidate and parties leaders, not any council candidate.

**Comment by gl1000007** [comment]
I think It's much more complicated. For example:
2 kinds of lists: idependent and party supported - does the DB has to change? How we'll display it to the users? Should we add a parties page? etc.
Should we let any list member other than the head of the list answer questions?
When a candidate answers a question, is he/she answers as a candidate or as the list he/she is leading, or both?
Even if what's written here is not accurate, this issue involves a large change, both in code and interface, so I think we should discuss it tomorrow at the meeting.

**Comment by daonb** [comment]
So... we need to change this.  I agree with lotan that the best approach will be to let only party leaders answer questions, as it's almost always their opinion that matters.  The party is important only to let the user know what he should vote for if he likes the candidates answers. 
We need to redesign the registration interface with a focus on candidates @gl1000007 can you do it?

**Comment by gl1000007** [comment]
Also, https://github.com/hasadna/open-shot/issues/146 https://github.com/hasadna/open-shot/issues/56

**Comment by gl1000007** [comment]
A stupid question - If we don't let candidates answer questions, then what do they do in the site?
From @daonb 's last comment, one can conclude that its sufficient for party members to use the normal user type (citizen), and for users to know what to vote for, we'll add: 1. characters of the list at some strategic locations (for example in the [candidate widget](https://github.com/hasadna/open-shot/issues/209)), 2. a new list page and link to it from all its member profiles.

**Comment by lotan1** [comment]
When I tried last time to answer questions at מעלה אבק I succed,
But its true we dont support candidates now,
we should by ראש השנה
Were are we standing now with it?

I suggest, lets develop those issues
-design for candidates page, by same basic tamplate for municipality and
mayor
-candidates register form, as a second page of registering, by same
tamplate as well
-create the procedure for localadmin to create the basic register
-view candidates by the info they enterd, if they wrote name for yellow not
we'll view it, if they paste youtube we'll view it, etc.

2013/8/30 Gilad L notifications@github.com

**Comment by daonb** [comment]
I think we'll trust candidates for the start. By making the candidates wait
we add unnecessary red tape. the simplest way is to approve candidates
automaticlly and trust the editor to quickly remove jokers.
As for the candidates page, I think I have everything I need from open
knesset. There's a `links` app the allows you to attach as many URL as you
like to any objects. In oknesset we use it to keep the MKs facebook,
twitter, youtube, etc... and I've already imported it into this project.
As for the parties, we have the fields on the `CandidateList` model,
herehttps://github.com/hasadna/open-shot/blob/dev/polyorg/models.py.
Actually, party is the most important one. Candidates I can just use the
links and I'll use oembed http://oembed.com/ to spread their links
content using isotope http://isotope.metafizzy.co/.

On 31 August 2013 11:49, lotan1 notifications@github.com wrote:

> When I tried last time to answer questions at מעלה אבק I succed,
> But its true we dont support candidates now,
> we should by ראש השנה
> Were are we standing now with it?
> 
> I suggest, lets develop those issues
> -design for candidates page, by same basic tamplate for municipality and
> mayor
> -candidates register form, as a second page of registering, by same
> tamplate as well
> -create the procedure for localadmin to create the basic register
> -view candidates by the info they enterd, if they wrote name for yellow
> not
> we'll view it, if they paste youtube we'll view it, etc.
> 
> 2013/8/30 Gilad L notifications@github.com
> 
> > Now designing the new Candidate page.
> > A stupid question - If we don't let candidates answer questions, then
> > what
> > do they do in the site?
> > From @daonb https://github.com/daonb 's last comment, one can
> > conclude
> > that its sufficient for party members to use the normal user type
> > (citizen), and for users to know what to vote for, we'll add: 1.
> > characters
> > of the list at some strategic locations (for example in the candidate
> > widget https://github.com/hasadna/open-shot/issues/209), 2. a new
> > list
> > page and link to it from all its member profiles.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/hasadna/open-shot/issues/126#issuecomment-23582482>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/126#issuecomment-23603045
> .

## 

http://yeda.us/daonb

**Comment by tbrisker** [comment]
basic candidate input is now available to editors via #285. please test before sending editors to work.

**Comment by tbrisker** [comment]
#302

**Comment by tbrisker** [comment]
Currently editors add candidates, and candidates can also add other candidates to their own list.
Closing this issue - open new issues for other methods of adding candidates. (invites? self-nomination?)
