### ISSUE TITLE
Make URLs Short, Pretty and sharable

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#128]
Many URLs contain Hebrew strings, such as  questions and locality names. This makes URLs very long, and pretty ugly (as a result of of mis-decoded text).

Take this for example:
http://oshot.hasadna.org.il/%D7%92%D7%9F-%D7%99%D7%91%D7%A0%D7%94/qna/%D7%9E%D7%94-%D7%A2%D7%9E%D7%93%D7%AA%D7%9A-%D7%91%D7%A0%D7%95%D7%A9%D7%90-%D7%91%D7%A0%D7%99%D7%99%D7%94-%D7%9C%D7%92%D7%95%D7%91%D7%94/

I suggest to replace all the non-english strings in URLs with some kind of unique identifier, like:
QuestionID=[int], LocalityID=[int]
or something like YouTube's URL structure: https://www.youtube.com/watch?v=45X6EyqXa2s (broken)

I assume the existing DB already has that kind of field names, so we can use them.

**Comment by gl1000007** [comment]
Another relevant issue - putting it here instead of opening a new one:
URL inconsistency between a locality's questions and candidates pages

Take Tel Aviv Jaffa for example:

URL for questions is:
http://oshot.hasadna.org.il/97/qna/

URL for candidates is:
http://oshot.hasadna.org.il/%D7%AA%D7%9C-%D7%90%D7%91%D7%99%D7%91-%D7%99%D7%A4%D7%95/candidates/

first version is better.

**Comment by daonb** [comment]
According to Paul from the open-muni project:

"We use Hebrew slugs, just like wikipedia and any other website with a
slight interest in search engine results and SEO.

Search engines, browsers, and most social media sites render the strings in
readable Hebrew."

On 8 August 2013 17:50, Gilad L notifications@github.com wrote:

> Another relevant issue - putting it here instead of opening a new one:
> URL inconsistency between a locality's questions and candidates pages
> 
> Take Tel Aviv Jaffa for example:
> 
> URL for questions is:
> http://oshot.hasadna.org.il/97/qna/
> 
> URL for candidates is:
> 
> http://oshot.hasadna.org.il/%D7%AA%D7%9C-%D7%90%D7%91%D7%99%D7%91-%D7%99%D7%A4%D7%95/candidates/
> 
> first version is better.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/128#issuecomment-22328753
> .

## 

http://yeda.us/daonb
