### ISSUE TITLE
suggested tabs addition to header

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#129]
The header tab includes: שאלות, מועמדים ואודות
And can include: תגיות וישובים, as well.

**Comment by gl1000007** [comment]
for יישובים we already have a dropdown list. Do you think of any new related content we should put into the site?

תגיות is interesting. I think about a tag-cloud that will show popular issues at the locality level or nation level.

If there are more ideas, I think we should split this issue into 2, and discuss each page seperately.
