### ISSUE TITLE
Notify user of redirection when trying to ask a question in a different locality

### ISSUE THREAD

**Issue by tbrisker** [hasadna/open-shot#130]
Currently, when a user tries asking a question in a different locality then the one he listed on his profile, he is redirected to asking in his own locality without any notification.

**Comment by gl1000007** [comment]
On the new page, we can add a yellow stripe with this:
"מצטערת, ניתן להעלות שאלה רק ביישוב שלכם. הועברתם ל[תל אביב]."

**Comment by daonb** [comment]
I've changed it so the button will show only in your locality or the global
scope.  When you view a locality that is different then your own, it
doesn't make sense to show the button so we don't.

On 6 August 2013 13:02, Gilad L notifications@github.com wrote:

> On the new page, we can add a yellow stripe with this:
> "מצטערת, ניתן להעלות שאלה רק ביישוב שלכם. הועברתם ל[תל אביב]."
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/130#issuecomment-22169045
> .

## 

http://yeda.us/daonb

**Comment by gl1000007** [comment]
Maybe something like this:
![ask a question gan yavne](https://f.cloud.github.com/assets/5072931/923293/120b1f6e-ff44-11e2-9614-5d3910494d5a.PNG)
This kind of button can be placed on **any** page, excluding the "ask" page itself, and still avoid the error of asking outside your locality.
I think this button is one of the main call-to-actions on the site, therefore we should display it in any opportunity we have.

**Comment by gl1000007** [comment]
P.S.
https://github.com/hasadna/open-shot/issues/134

**Comment by gl1000007** [comment]
@daonb +1
