### ISSUE TITLE
Tags should not be mandatory when creating a question

### ISSUE THREAD

**Issue by danielhers** [hasadna/open-shot#131]
When creating a question, you cannot submit it if you did not specify any tag. This should not occur.

**Comment by lotan1** [comment]
should we limit tags to 20 charcters so it wont mess the tag list?

**Comment by daonb** [comment]
You can add a new issue for it, but close this one...

**Comment by gl1000007** [comment]
https://github.com/hasadna/open-shot/issues/150
pls close.
