### ISSUE TITLE
Make the ask button visible from every page.

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#134]
Even for logged-out users.
This is our main call-to-action, therefore we should emphasize it.

**Comment by daonb** [comment]
well, the logic behind the interface is that pages are displayed in a certain scope - aka locality - or in the global scope.  The first line on the page specifies the scope and should probably be highlighted in a special way.
Once the user is in a certain scope, he will not be able to perform action relating to other scopes, other than jumping to them.
Following this logic, the button to ask a question could be displayed in the global scope and in the scope of the users locality, but not in other locality as it breaks the interface's logic.

And, it's not the man call-to-action. If it will be, we'll get a ton of question with very few people joining in.  The main call-to-action is to join a question, not to ask one.

**Comment by gl1000007** [comment]
Sounds logical to me.

(irrelevant material deleted)

**Comment by daonb** [comment]
+1. just copy it to a new issue "Improving page titles" and close this one.

On 7 August 2013 18:00, Gilad L notifications@github.com wrote:

> Sounds logical to me.
> 
> We can highlight the scope by writing it in the main title in the page,
> like we already do in the questions' pages:
> first one is locality specific and the second is nation wide:
> שאלות למועמדים באבו בסמה
> שאלות למועמדים בבחירות המקומיות
> 
> We can have:
> מועמדים באבו בסמה
> מועמדים בבחירות המקומיות
> 
> same goes with תשובות.
> 
> In general:
> [page title] at [locality name]
> [page title] at local elections
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/134#issuecomment-22257477
> .

## 

http://yeda.us/daonb

**Comment by gl1000007** [comment]
Sorry for this. It will take me some time to get used to GitHub practices.
https://github.com/hasadna/open-shot/issues/137
