### ISSUE TITLE
Default locality should be something meaningful like "בחרו יישוב".

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#136]

**Comment by daonb** [comment]
it really is "כל הארץ", no?

On 8 August 2013 15:44, Gilad L notifications@github.com wrote:

> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/136
> .

## 

http://yeda.us/daonb

**Comment by gl1000007** [comment]
It is, but I was thinking on it -
"כל הארץ" is just an informative text, whereas "בחרו יישוב" is also a call to action.
There is no one right way to do it, it's my personal opinion.

I found some existing sites that mix the 2 wording methods, like
http://www.yad2.co.il/Yad2/Yad2.php
http://www.2eat.co.il/

And other sites that use the call-to-action method, like
http://www.alljobs.co.il/

So you can choose whatever you like.

**Comment by lotan1** [comment]
its fun!
