### ISSUE TITLE
Generate some sort of a site map / tree view

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#139]
Some issues relate to the entire site, including every single page in it.
Take for example https://github.com/hasadna/open-shot/issues/133 and https://github.com/hasadna/open-shot/issues/137.

In order to be sure we went through all the pages, a site map can assist.
If not a site map, any solution which provides a way to linearly go through all the pages, will be appreciated.

P.S.
Do you know who else love site maps? Search engine crawlers. They really do!

**Comment by daonb** [comment]
We already have a sitemap for the crawlers, it's here:
http://oshot.hasadna.org.il/sitemap.xml

On 8 August 2013 17:24, Gilad L notifications@github.com wrote:

> Some issues relate to the entire site, including every single page in it.
> Take for example #133 https://github.com/hasadna/open-shot/issues/133and
> #137 https://github.com/hasadna/open-shot/issues/137.
> 
> In order to be sure we went through all the pages, a site map can assist.
> If not a site map, any solution which provides a way to linearly go
> through all the pages, will be appreciated.
> 
> P.S.
> Do you know who else love site maps? Search engine crawlers. They really
> do!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/139
> .

## 

http://yeda.us/daonb

**Comment by gl1000007** [comment]
ok but what about one for humans? especifically the dev team which needs to get trough all the pages finding bugs.

**Comment by daonb** [comment]
IMO, it's more trouble than its worth. Maps are OK for static sites but in
our case it's too complex to be usuable.
