### ISSUE TITLE
Server Error 500 while changing user settings at admin > Auth > Users >

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#140]

**Comment by daonb** [comment]
Seems like the problem is that the current Profile is not displayed and the admin tries to create a new profile when the user saves the user.

**Comment by lotan1** [comment]
לא רוצה לבאס אבל אני עדיין מקבל הודעות שגיאה כאלו
על כל שינוי של בחצי העמוד של פרופייל בתוך שינוי יוזר
 על שני שינויים שבדקתי על שני יוזרים שונים ועל ידי שני יוזרים שונים שבדקתי כרגע
בהצלחה..

**Comment by daonb** [comment]
סגרתי בטעות.  בינתיים לא הצלחתי לתקן את הבעיה ועברתי לבעיות פשוטות יותר...

**Comment by lotan1** [comment]
יש שם עוד כמה דברים שתוקנו!
