### ISSUE TITLE
local moderator can delete any candidate or question in the site

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#142]

**Comment by daonb** [comment]
How? using admin?

On 12 August 2013 19:47, lotan1 notifications@github.com wrote:

> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/142
> .

## 

http://yeda.us/daonb

**Comment by lotan1** [comment]
כן, כל משתמש שמקבל הרשאת רכז ישוב, כלומר הרשאה למחיקת שאלות,
יכול למחוק שאלות גם כשהוא קורא אותן באתר וגם בפאנל אדמין
לדעתי, ומתברר שאני חשדניסט יותר מהמקובל, זה בעייתי גם מבחינת זדון, וגם בשוגג.

**Comment by daonb** [comment]
אז מה שצריך לשנות זה שממשק הניהול של עורכים יוגבל כך שהם יוכלו לערוך רק
פרטי מידע הנוגעים לרשות שלהם. נכון?

2013/8/14 lotan1 notifications@github.com

> כן, כל משתמש שמקבל הרשאת רכז ישוב, כלומר הרשאה למחיקת שאלות,
> יכול למחוק שאלות גם כשהוא קורא אותן באתר וגם בפאנל אדמין
> לדעתי, ומתברר שאני חשדניסט יותר מהמקובל, זה בעייתי גם מבחינת זדון, וגם
> בשוגג.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/142#issuecomment-22629566
> .

## 

http://yeda.us/daonb

**Comment by lotan1** [comment]
כן, אם זה ניתן זה יפתור את הבעיה.
גם בממשק הניהול וגם מתוך האתר הרגיל.
כך לצרף "רכז יישוב" לא ייחיב לעשות לו בדיקת אופי..

**Comment by daonb** [comment]
בדקתי. ממשק הניהול לא נגיש לעורכים מקומיים

**Comment by lotan1** [comment]
לא צריך ממשק ניהול,
המחיקה יכולה להעשות בתוך האתר באמצעות הדגל האדום על שאלות בכל עיר ובעמוד
המועמדים של כל עיר

2013/8/22 benny daon notifications@github.com

**Comment by lotan1** [comment]
yet open
local moderator define by "is editor" on admin panel, without "סטטוס איש צוות"

**Comment by daonb** [comment]
this is upposed to be fixed. can someone test this?
