### ISSUE TITLE
שינוי הגדרות עצמי ב"ערוך פרופיל"

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#143]
1. משתמש יכול להגדיר עצמו כמועמד בדיעבד
2. מועמד שנכנס לעריכת פרופיל - ברירת המחדל היא שסימון ממועמד מוסר והוא יהפוך למשתמש
3. משתמש לא יכול לשנות בדיעבד את מקום מגוריו - איך מתמודדים עם הקלדה שגויה
4. מועמדים וראשי רשימות צריכים אופציות נוספות בעמד הפרופיל שלהם

**Comment by daonb** [comment]
לא ברור מה הבעיה ומה השינוי שצריך לעשות.  נראה לי שמתחבאים כאן יותר
מ"עניין" אחד

2013/8/12 lotan1 notifications@github.com

> 1. משתמש יכול להגדיר עצמו כמועמד בדיעבד
> 2. מועמד שנכנס לעריכת פרופיל ברירת המחדל היא שסימון ממועמד מוסר והוא
>    יהפוך למשתמש
> 3. משתמש לא יכול לשנות בדיעבד את מקום מגוריו - איך מתמודדים עם הקלדה
>    שגויה
> 4. מועמדים וראשי רשימות צריכים אופציות נוספות בעמד הפרופיל שלהם
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/143
> .

## 

http://yeda.us/daonb

**Comment by lotan1** [comment]
אכן כנראה מדובר ביותר מעניין אחד שכולם קשורים לעריכת פרופיל לאחר התחברות
1.  כשם שמשתמש לא יכול לשנות לעצמו את הישוב בדיעבד, אין סיבה שישנה את מהותו הפוליטית בדיעבד, כדאי לנעול
2. כרגע מועמד שנכנס לכתוב על עצמו שהוא גם יודע לנגן גיטרה יכול להימחק בטעות מלהיות מועמד, ברירת מחדל צריכה להיות שמורה על ההגדרת משתמש הקודמת (בהנחה שזה לא נעול מסעיף 2)
3. סוגיית תיקון שגיאות שעולה מתוך סעיף 1
4. זה באמת דיפרנט אישיו, צריך לדעתי לשפר את קליטת המועמדים את אימותם ואת עמוד המועמד

**Comment by daonb** [comment]
מה שחשוב לזכור זה שהעניינים כאן קיימים כדי שכל מפתח יוכל לקחת עניין ולקדמו.
 גם אם ש שניים או שלושה עניינים קשורים, עדיף להפריד ולהגדיר כל עניין בנפרד
ובצורה ברורה, כדי שגם מפתח שלא מכיר את ההסטוריה ולא מכיר אותי או אותך יוכל
להבין מה צריך לעשות.
