### ISSUE TITLE
user avatar size can change between diffrent pictures and browsers

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#144]

**Comment by lotan1** [comment]
1. the avatar size should be permanent relatively.
2. a defaulet avatar for any user should be set, to keep the questions view design constant for all questions.
3. the avatar of candidates answers shuld be at least the same size of the questioners.

**Comment by gl1000007** [comment]
Let's see if I got you right. What you mean is:
There should be a fixed size for avatars on the right side of the page, both of citizens and candidates.

Technically, we should make them square (42x42 px) by using the [Fit-in](http://www.connsphotolab.com/2009/01/26/fill-in-and-fit-in-explained/) method.

I'm not sure what "permanent relatively" means.

**Comment by lotan1** [comment]
אכן כך
קבוע יחסית היה בהקשר של תלות בזום שהמשמתמש נמצא בו
אבל בעיקר
 אם לא תסכימו להצעתי שהתמונת מועמדים משיבים צריכה להיות באותו הגודל של תמונת השואלים, 
אז קבוע בשני גדלים שונים כפי שזה קיים בדרך כלל עכשיו.

קביעת התמונת ברירת מחדל גם לתמונות חסרות זה סבבה?

**Comment by lotan1** [comment]
התמונות משתנות באופן הכי בעייתי באקספלורר

**Comment by daonb** [comment]
ברור. ובלי שיש לי גישה לאקספלורר אני יכול להגיד לך קזה משתנה בין גרסאות של
אקספלורר. אין לנו זמן וחשק לקקה הזה, תן לאקספלורר למות לבד בפינה ולמשתמשיו
לסבול.

**Comment by lotan1** [comment]
אני רואה שנשברת, או שזה הסתדר באקספלורר בלי שרצית, יופי! אני בטוח ש-9
משתמשי האקספלורר שכבר פועלים באתר יודו לך (אם רק היו לאנשים מהסוג הזה
הכישורים החברתיים לכך).
יש עדיין את העניין של להדביק תמונת ברירת מחדל לקישורים שבורים או חסרים, הנה:
![screenhunter_58 aug 21 23 34](https://f.cloud.github.com/assets/4595165/1004420/cd3e1800-0aa1-11e3-96d9-7c8a5c63fa23.jpg)

**Comment by lotan1** [comment]
ועניין נוסף בהקשר, חיבור מחודש באמצעות פייסבוק מחזיר את התמונה לתמונה בפייסבוק, גם אם שונתה ידנית בעמוד הפרופיל

**Comment by daonb** [comment]
זה לא שיחה חופשית כאן וההקשר פחות חשוב מהגדרה מדויקת של העניין וסגירה
כשהעניין נפתר.  אם בתהליך גילית עניין חדש, סגור את העניין הנוכחי ופתח חדש,
אחרת יהיה ברדק.

2013/8/22 lotan1 notifications@github.com

> ועניין נוסף בהקשר, חיבור מחודש באמצעות פייסבוק מחזיר את התמונה לתמונה
> בפייסבוק, גם אם שונתה ידנית בעמוד הפרופיל
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/144#issuecomment-23072270
> .

## 

http://yeda.us/daonb
