### ISSUE TITLE
לנעול את הגדרת המשתמש כמועמד או בוחר לאחר התחברותו הראשונית

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#145]
כמו את בחירת היישוב, זה לא דברים שמשתנים בדיעבד, כך שמוטב שלא ישתנו בטעות.

**Comment by gl1000007** [comment]
וגם: אם משתמש מסמן את עצמו כמועמד, זה צריך לעבור אישור של עורך מקומי או אדמין כלשהו אחר. עד אז, המשתמש החדש לא יכול לכתוב שאלות או תשובות.

**Comment by lotan1** [comment]
וגם לקבל הפנייה להשלמת פרטי מועמד על פי התבנית החדשה
בכל מקרה האפשרות תצטרך להינעל לאחר בחירה כמו בחירת ישוב

**Comment by daonb** [comment]
@lotan1,
 הוספתי שתי שורות כדי לענות על הבקשה המקורית. עדיף להמנע מ"וגם", עניינים הם בחינם, תמיד עדיף לפתוח אחד חדש...
