### ISSUE TITLE
Add a link to user registration with no facebook/twitter

### ISSUE THREAD

**Issue by daonb** [hasadna/open-shot#148]
Should point to /accounts/register/

**Comment by daonb** [comment]
It's probably a design issue now - On the login page, I added a link below twitter to allow the user to register by himself. It's small on purpose as we want ppl to signin using facebook/twitter, but maybe it's too small...

**Comment by lotan1** [comment]
good!
now need to add title of "התחברות ראשונית" same as "היכנסו"
and rephrase "הירשמו עצמונית" to somthing like "אימות הרשמה באמצעות כתובת
מייל"

2013/8/20 benny daon notifications@github.com
