### ISSUE TITLE
charcters limit on tags

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#150]
should we limit tags to 20 charcters so it wont mess the tag list?

**Comment by gl1000007** [comment]
+1
Just saw [12345678901234567890](http://oshot.hasadna.org.il/qna/tags/12345678901234567890/) :)
This is the largest line length before it breaks.
Of course there are some exceptions, like שששששששששששששששששששש, but they are usually Spam and we'll be able to delete them manually.

**Comment by gl1000007** [comment]
note that something needs to be done with existing long tags, such as "12345678901234567890" above.
make sure that the code refers to those tags (options: delete tag, get first 20 characters, etc.), or they would have to be deleted manually.

**Comment by lotan1** [comment]
אני אנקה ידנית הכל בהמשך השבוע
וכמובן, אנסה להכניס הכל מחדש..

2013/8/19 Gilad L notifications@github.com
