### ISSUE TITLE
loosing locality after clicking /about

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#151]
משתמש תושב עיר לדוגמא לוחץ על טאב "אודות" לאחר מכן על טאב "שאלות"
יהיה עליו לבחור כעת את עיר לדוגמא מחדש מהרשימה למעלה.

**Comment by gl1000007** [comment]
+1

**Comment by lotan1** [comment]
עדיין פתוח

**Comment by daonb** [comment]
There's a question of UX here.  The about is a global page and maybe the
right solution is to move it to the footer of the page.  clicking it will
move the user back to the global scope, loosing the locality like is
happening today, but it will make sense.

**Comment by lotan1** [comment]
זה רעיון טוב,
אולי אפשר דווקא להוריד את זה רמה ולייצר עמוד אודות מעט דינמי שכותב גם לינק
ליצירת קשר עם העורך המקומי בעיר שלך.
בכל אופן, לדעתי משתמש לא צריך "לאבד" את העיר שלו אלא אם הוא ממש רוצה,
בהנחה שאנחנו פונים לקהל הרחב, לרובו ממש לא אכפת מה קורה בערים אחרות.

2013/8/20 benny daon notifications@github.com

**Comment by daonb** [comment]
why is the issue closed?

**Comment by lotan1** [comment]
because its fixed
http://localshot.org.il/p/about/?entity=224
can open new issue with the improvement suggestion

2013/8/21 benny daon notifications@github.com
