### ISSUE TITLE
In question detail page display the list of question supporters

### ISSUE THREAD

**Issue by daonb** [hasadna/open-shot#153]
Today, there's no way of knowing who are the users the support a question.

**Comment by gl1000007** [comment]
![support question](https://f.cloud.github.com/assets/5072931/1207423/5f473b84-25b7-11e3-9362-868535197d46.png)

**Comment by daonb** [comment]
+1, plus a popup with the user's name when mouse is over an avatar

**Comment by gl1000007** [comment]
The interaction should be identical to existing avatar images.
If possible, use the existing 42x42 images and their code for this.

**Comment by danielhers** [comment]
Anyone on it? No? I'll do it then.

**Comment by danielhers** [comment]
Should the question author be included? It already appears on the right...

**Comment by gl1000007** [comment]
Yes. If a user writes a question, it's logical to say that he/she supports it.

**Off-Topic Warning**
Plus, like Facebook does, if the logged in user supports the question, their avatar will be the first, then their friends, then all the other supporters. If it can be applied in code, I'll open a separate issue for it. We can wait with it until after the elections.

-------- הודעה מקורית --------
מאת: Daniel Hershcovich notifications@github.com 
תאריך: 11/10/2013  16:55  (GMT+02:00) 
אל: hasadna/open-shot open-shot@noreply.github.com 
עותק: Gilad L gl1000007@gmail.com 
נושא: Re: [open-shot] In question detail page display the list of question supporters (#153) 

Should the question author be included? It already appears on the right...

**Comment by daonb** [comment]
The supporters scroll bar looks silly, why not keep the list of supporters going?
![selection_025](https://f.cloud.github.com/assets/36852/1349647/96e069e6-36f4-11e3-8dd6-5e8056e71484.png)

**Comment by danielhers** [comment]
It has a scrollbar in the [spec](https://docs.google.com/file/d/0B3yaQaorsX55dnAyeDI2aXZNek0/edit). @gl1000007 , what do you think? Maybe just increase the height?

**Comment by gl1000007** [comment]
Scrollbar is not mandatory + since there is nothing below the supporters list, we can let it wrap until (minimum):
*it ends, or
*up to the height of the viewport minus the top bar.

If applying this is too complicated, make the list wrap until it endswithout considering the viewport.

Another thing - all of the avatars have to be the same size. Please make them circle (not eliptic). That way we can also save some vertical space.

**Comment by gl1000007** [comment]
Forgot the footer...
Just let the list wrap until it ends.
