### ISSUE TITLE
users cant edit their own questions 

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#155]
מקבל: מצטערת, השאלה כבר קיימת
ניתן לשנות את השאלה רק אם משנים את כותרתה

**Comment by lotan1** [comment]
אפשרות העריכה עובדת טוב
אבל טעיתי כשסגרתי את זה,
עדיין חייבים לשנות את כותרת השאלה כדי שהיא תוכל להישמר,
מה שיאתגר מדי את המשתמש הממוצע

**Comment by daonb** [comment]
It's better to close an issue and open a more accurate new one
