### ISSUE TITLE
new tags problem

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#156]
כשמכניסים שאלה חדשה, אם מקלידים רצף אחד עם רווחים כמו 

"תג עם רווח" 
מקבלים 3 תגיות נפרדות!

"תג עם רווח, עוד תג עם רווח"
עובד יופי!

**Comment by daonb** [comment]
hmm... you should search before you add a new issue, in #121 we had a lengthy discussion. If you must re-open that ticket.

**Comment by lotan1** [comment]
to much to search for me
ill open it
