### ISSUE TITLE
create the local admin panel inside the site

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#164]
המנהלים המקומיים (להלן הגננים) צריכים להיות עמוד טווח מרכזי בחשמביר בתפעול והפצה
הגננים (200 בשאיפה) ברובם אינם אנשי תוכנה וחוששים מעמוד הניהול
הגננים לא עוברים אימות זהות ויכולות רציני במיוחד כך שצריך למנוע מהם את האפשרות לפגוע בתוכן של ערים לא להם.

כדאי לייצר להם עמוד גננים עירוני ובו:
הגנן צריך להיות מסוגל לשלוט בעריכת ומחיקת: תגיות, שאלות, משתמשים.
הגנן צריך להיות מסוגל להזמין מועמדים ולפתוח להם עמוד טיוטה.
הגנן צריך להיות מסוגל להסיר דגלים.
הגנן צריך להיות מסוגל לשלוח הודעות למשתמשים.

**Comment by tbrisker** [comment]
please separate this to issues for every part. some are already done, some won't happen. closing.

**Comment by gl1000007** [comment]
Maybe we can find time for it at the Hackathon.
Until then, @lotan1 if you have time, you can make more detailed requirements list and post it to drive.
