### ISSUE TITLE
Dev questions/Issues

### ISSUE THREAD

**Issue by Suberri** [hasadna/open-shot#168]
I have a dev question and I am not sure where to post it. 
How about adding dev tag to the issue list or creating a Dev page

**Comment by daonb** [comment]
use the group: localshot@googlegroups.com

On 21 August 2013 16:03, Suberri notifications@github.com wrote:

> I have a dev question and I am not sure where to post it.
> How about adding dev tag to the issue list or creating a Dev page
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/168
> .

## 

http://yeda.us/daonb

**Comment by Suberri** [comment]
Thanks

On Wed, Aug 21, 2013 at 10:47 PM, benny daon notifications@github.comwrote:

> use the group: localshot@googlegroups.com
> 
> On 21 August 2013 16:03, Suberri notifications@github.com wrote:
> 
> > I have a dev question and I am not sure where to post it.
> > How about adding dev tag to the issue list or creating a Dev page
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/hasadna/open-shot/issues/168>
> > .
> 
> ## 
> 
> http://yeda.us/daonb
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/168#issuecomment-23044554
> .

## 

Cheers
Moshe
