### ISSUE TITLE
Regarding web page space efficiency   

### ISSUE THREAD

**Issue by Suberri** [hasadna/open-shot#169]
Looking at the Q&A page it caught my eyes that on each of the questions about 95% of the space is occupied repeatedly with an oversized user pic. Thus, on a single page only two questions can be seen. 
I am not sure what the user pic adds to the discussion, but if needs to be there a  smaller icon should be considered.

**Comment by lotan1** [comment]
Dosnt it gives it the space needed between questions?
#144

**Comment by tbrisker** [comment]
seems like this was fixed already.
