### ISSUE TITLE
Aֻdd candidate's profile second page

### ISSUE THREAD

**Issue by daonb** [hasadna/open-shot#170]
When a user checks he's a candidate on his first pass at editing his profile, he should be displayed a second page with a form asking him to fill additional info, such as...

**Comment by lotan1** [comment]
such as
name
picture
letters of candidate or party
personal info (short)
party info (short)
additional info (long)
single youtube
facebook page/user
personal contact details for admins only

2013/8/21 benny daon notifications@github.com

**Comment by daonb** [comment]
I think we should separate user, candidate and party forms IMO, the candidate form is just about links, allowing candidates to create a collection of all their online resources. 
As for party, I stole the [code from the 'polyorg' app I coded for oknesset](https://github.com/hasadna/openshot/blob/dev/polyorg/models.py#L6) and if he's the first, I'll let him add the party

**Comment by lotan1** [comment]
I want to discuss it for the best comprehensive solution, maybe monday?

2013/8/22 benny daon notifications@github.com

**Comment by tbrisker** [comment]
#302

**Comment by tbrisker** [comment]
obsoleted by new layout by @gl1000007 and #318
