### ISSUE TITLE
sort candidates according to the number of their answers

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#172]
![screenhunter_58 aug 21 23 41](https://f.cloud.github.com/assets/4595165/1004448/7453c1da-0aa2-11e3-9edd-a24b45a41b45.jpg)

**Comment by daonb** [comment]
It's now on random order which seems like the fair thing to do. no?

**Comment by lotan1** [comment]
we discuss it monday, we prefer the answering motivation that will grow
from the order by answers.
although yet need to create sort of separation between mayor candidates and
municipallity candidates.

2013/8/22 benny daon notifications@github.com
