### ISSUE TITLE
העמודים שעיצבתי

### ISSUE THREAD

**Issue by nirwe** [hasadna/open-shot#174]
![main](https://f.cloud.github.com/assets/5282166/1005101/02d97cd4-0ab1-11e3-88e2-e09fb34323ad.png)
![qanda](https://f.cloud.github.com/assets/5282166/1005102/02dc3672-0ab1-11e3-9e8e-82525ce09dd8.png)
![nominees](https://f.cloud.github.com/assets/5282166/1005100/02dba09a-0ab1-11e3-96fc-6cb0555221cb.png)
![nominee](https://f.cloud.github.com/assets/5282166/1005103/02da8138-0ab1-11e3-82fe-df3fca4293b6.png)

**Comment by Suberri** [comment]
Nice work

On Thu, Aug 22, 2013 at 1:28 AM, nirwe notifications@github.com wrote:

> [image: main]https://f.cloud.github.com/assets/5282166/1005101/02d97cd4-0ab1-11e3-88e2-e09fb34323ad.png
> [image: qanda]https://f.cloud.github.com/assets/5282166/1005102/02dc3672-0ab1-11e3-9e8e-82525ce09dd8.png
> [image: nominees]https://f.cloud.github.com/assets/5282166/1005100/02dba09a-0ab1-11e3-96fc-6cb0555221cb.png
> [image: nominee]https://f.cloud.github.com/assets/5282166/1005103/02da8138-0ab1-11e3-82fe-df3fca4293b6.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/174
> .

## 

Cheers
Moshe

**Comment by nirwe** [comment]
Thanks!

**Comment by tbrisker** [comment]
Closing due to newer designs making most of this issue obsolete.
