### ISSUE TITLE
When joining a question the counter should be updates

### ISSUE THREAD

**Issue by daonb** [hasadna/open-shot#175]
today, you have to refresh the screen so see your upvote

**Comment by lotan1** [comment]
I noticed that you dont have to refresh if you are not the first supporter of the question, only from 0 to 1.

**Comment by danielhers** [comment]
I thought the person asking the question is always a supporter, so the counter can never be zero...

**Comment by gl1000007** [comment]
Tested it now on several questions, working :)

[Another issue](https://github.com/hasadna/open-shot/issues/192), Not sure if it's urgent now

**Comment by lotan1** [comment]
maybe we should start the counter on 1, that will solve this issue

2013/8/25 Gilad L notifications@github.com

**Comment by danielhers** [comment]
I think it starts on 1. The problem was with the transition from 1 to 2, which my commit fixes.
