### ISSUE TITLE
Password Reset does not work

### ISSUE THREAD

**Issue by Suberri** [hasadna/open-shot#178]
Trying to reset my password; getting the following error msg:
חשבון המשתמש המשוייך לכתובת דוא"ל זו אינו יכול לאפס את הסיסמה

**Comment by daonb** [comment]
What's the email you used to register?

**Comment by lotan1** [comment]
Didnt work for me as well on saturday for some registerd emails of mine

2013/9/1 benny daon notifications@github.com

**Comment by tbrisker** [comment]
also #162 while at it.

**Comment by danielhers** [comment]
I think this is a problem in our version of Django, where the Reset Password form raises an exception if at least one of the users that have the specified username (there may be more than one) does not have a usable password (e.g. if they have registered with Facebook and not set a password).
I'm pretty sure the newest version of Django does not have this problem, as [this](https://github.com/django/django/commit/2f4a4703e1931fadf5ed81387b26cf84caf5bef9) seems to make the form simply ignore users with no password.
Therefore, maybe updating https://github.com/hasadna/django will solve the problem.
@daonb , do you want to try?

**Comment by tbrisker** [comment]
seems like the problem with the mailer on the server caused this not to work. now fixed.
