### ISSUE TITLE
new "הירשמו" page has no fb/tw login buttons

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#179]

**Comment by gl1000007** [comment]
searched for "twitter", "facebook" and "social" before posting a new issue, still duplicate! ugh.
From now on, please use full names so issues can be more searchable.

Copied from 191 (Now Closed):
In "register" page, new users only see the option of registering using email, no mention for any social network.
Just copying them from the "Enter" page (without "הירשמו עצמנית") should be enough.
