### ISSUE TITLE
url not found on facebook / twitter login button 

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#180]
http://localshot.org.il/login/facebook/
Not Found
The requested URL /login/facebook/ was not found on this server.

http://localshot.org.il/login/twitter/

**Comment by danielhers** [comment]
Both work fine for me.

**Comment by gl1000007** [comment]
works fine for me too. pls close.

**Comment by daonb** [comment]
I think the problem is that the register page doesn't have the links. I
suggest we close this as 'invalid' and create a new issue to merge the
login and register pages.

**Comment by lotan1** [comment]
the problem isnt exist for the register page because it dosent include those buttons now,
and sloved on the login page
