### ISSUE TITLE
users cant change their avater

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#182]
http://localshot.org.il/avatar/change/
Not Found
The requested URL /avatar/change/ was not found on this server.

**Comment by gl1000007** [comment]
1
If anyone gets to this, I suggest [this layout](https://docs.google.com/file/d/0B3yaQaorsX55MFZVTW9DQVNnYlU/edit?usp=sharing)

2
not sure if its relevant
https://github.com/hasadna/open-shot/issues/193

**Comment by daonb** [comment]
It's still here. something's wrong with the S3 interface from our server.  When using S3 from my dev server it works, on the live server it fails. I'm on it.

**Comment by lotan1** [comment]
the avatars arent stable
cant explain
![Uploading ScreenHunter_58 Aug. 28 21.15.jpg . . .]()

**Comment by lotan1** [comment]
ok, looks better now

**Comment by daonb** [comment]
There was a missing jpeg library in the server which crashed the handling of jpeg avatars. That's because jpeg license is restrictive. Always use PNG when you can, because jpeg's screwed up license is crashing our servers...

**Comment by lotan1** [comment]
Nice to know
But Im afraid it will be difficult to eplain it to the world out there
Its works good now!
