### ISSUE TITLE
facebook manual sharing should include pictures

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#188]
can be our logo or the avatar that his content shared

**Comment by gl1000007** [comment]
I have nothing against Obama, but I think a logo is more appropriate for this location. isn't it?
![obama](https://f.cloud.github.com/assets/5072931/1022841/fec97d90-0db4-11e3-8896-9d861711f36f.PNG)

Maybe a larger version of https://ok-qa-media.s3.amazonaws.com/img/logo.png
Can we ask this from the graphic designer?

P.S.
This should be included in the next milestone.

**Comment by gl1000007** [comment]
Further to @lotan1,
I suggest the image will be, in that order:
- If it's a specific candidate or citizen's page, display the person's avatar, else
- For a Locality, display its symbol, else
- Display a Logo.

If time constraints exist and the code above is too complex, just use the same logo for all the pages.

**Comment by lotan1** [comment]
sounds like perfect order,
and the snap looks great as well

2013/8/25 Gilad L notifications@github.com

**Comment by lotan1** [comment]
If we can set what happans when user will share the domain, thats can be great for now
![screenhunter_59 sep 02 01 16](https://f.cloud.github.com/assets/4595165/1066824/ff3d512c-13bb-11e3-9f50-525e67449a21.jpg)

**Comment by lotan1** [comment]
must change!
![screenhunter_64 sep 29 20 47](https://f.cloud.github.com/assets/4595165/1233512/2d8a0b6e-292f-11e3-927d-d8d004e62a68.jpg)
![screenhunter_63 sep 29 20 46](https://f.cloud.github.com/assets/4595165/1233513/2d8e8da6-292f-11e3-81b0-5e2b051bf424.jpg)
![screenhunter_64 sep 29 20 46](https://f.cloud.github.com/assets/4595165/1233514/2dac5304-292f-11e3-98c7-403bf975c0c8.jpg)

**Comment by tbrisker** [comment]
related to #114

**Comment by tbrisker** [comment]
for now made our logo default for all pages as most users and all localities don't have an image yet. closing this issue - if we want to change this later open a new issue.

**Comment by tbrisker** [comment]
turns out FB doesn't allow specifying images on CDNs. will have to find a way to work around.

**Comment by tbrisker** [comment]
from facebook docs: 
We suggest that you give us an image of at least 600x315 pixels. However, bigger is better, so if you have a 1200x630 or larger image that you can use, please give it to us. Also, we recommend that you keep images as close to a 1.91:1 aspect ratio as possible to avoid cropping. (Note: image sizes must be no more than 5MB in size.) Note that you can include more than that one og:image in your object if you have more than one resolution available.
so - we need a logo that is the right proportions for it to look nice, once I figure out how to get it to display.

**Comment by tbrisker** [comment]
from mail:
כשאני שמה בפייסבוק קישור לעמוד של ירושלים בשו"ת המקומי, ה-thumbnail בתצוגה המקדימה הוא תמונה של עופר ברקוביץ'. יש סיבה שזה קורה? אפשר לטפל בזה? המועמדים האחרים לא מתלהבים מזה , ובצדק.

**Comment by Talbatz** [comment]
כן. צריך להוסיף תגיות של פייסבוק אופ גרף בהאדר של האתר

**Comment by lotan1** [comment]
אנחנו ממשיכים לקבל תלונות על עניין זה מהעורכים המקומיים
"רשימת שאלות (נתניה) | example.com"

**Comment by Talbatz** [comment]
Ok so let's get this done

Here's the relevant fb dev doc: https://developers.facebook.com/docs/opengraph/howtos/maximizing-distribution-media-content/

We need to upload a 1200x630 image to the website (i made one, it's quite basic, find it attached)
![og-image-localshot](https://f.cloud.github.com/assets/1596230/1307020/fdc858f8-31b8-11e3-95b7-8e27129bc6d7.jpg)

then we need to add an open graph meta tag like this:
[meta property="og:image" content="path/to/images/folder/image_name.jpg" /]
to the header area in base.html (replace square brackets, of course)

Can someone please add this image and code? i would have done it myself but i'm a lil' unconfident here in git being a n00b and all ;-)

**Comment by Talbatz** [comment]
While at it, there few other metadata tags missing in the header, like:

```
<meta property="og:title" content="...call the page's title..." />
<meta property="og:url" content="...page url here..." />
<meta property="og:site_name" content="אתר השות המקומי" />
<meta property="og:description" content="תוכן השאלה או תיאור כללי אחיד וגורף לכל האתר" />
<meta property="og:locale" content="he_IL" />
```

and of course there's the meta description tag that is missing, it is very important to seo!

```
<meta name="תוכן השאלה או תיאור כללי אחיד וגורף לכל האתר" />
```

these tags should be inserted into the page header and get populated with the appropriate data.

**Comment by tbrisker** [comment]
@daonb - can you handle adding the image? as it seems uploading it to the cdn where all the static files are located does not work (see above) - we need to make it available in the localshot domain and link to it from the og tag

**Comment by lotan1** [comment]
Actually the Issue should change to somthing like - make an invitable
facebook manual share

suggestions are to use our logo as default
and to change title from
רשימת שאלות (הוד השרון) | localshot.org.il and
https://www.facebook.com/?ref=logo#
אנחנו זוג צעיר ללא עזרה כספית מההורים אוהבים את העיר אך מחירי הדיור יקרים
מאוד https://www.facebook.com/?ref=logo# and
אמיר כוכבי (הוד השרון) | localshot.org.ilhttps://www.facebook.com/?ref=logo#
to
"השו"ת המקומי - הוד השרון" or somthing else

2013/10/10 tbrisker notifications@github.com

> andle adding the image? as it seems uploading it to the

**Comment by Talbatz** [comment]
@tbrisker i'm not sure that we must have the image hosted on our domain, I think a cdn would do just fine.
Please take into account that once a page has been shared on fb the data gets cached and it might take a while before we actually see the changes reflected on the walls in facebook where those pages are shared.

@lotan1 about using the logo image, facebook recommends to use a 1200x630 image (which gets you a larger view on fb walls) and the minimal recommended is 600x315 - hence i wouldn't recommend using a simple logo as the shared image. I agree that the 1200x630 image i attached before is far from perfect, let's improve it - any ideas @anyone?

**Comment by Talbatz** [comment]
here is the open graph image on hasadna.org.il server:

http://www.hasadna.org.il/wp-content/uploads/2013/10/og-image-localshot.jpg
