### ISSUE TITLE
A better alternative for Gravatar

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#193]
Most of our users just don't have Gravatar, and we won't be able to convince the masses to register to Gravatar. 

and now in a more detailed manner:
Display image from source:
- If user is registered via Facebook _and_ user image is not the default one, display Facebook profile pic, else
- If user is registered via Twitter _and_ user image is not the default one, display Twitter profile pic, else
- If user is registered via Email, Search Gravatar for user's email address. If no image or Gravatar's default image is returned,
- Display some kind of a default image. such as the site's logo (not Gravatar's default).

Short timed version: Just use Facebook. Code available in one of the former versions.

I think this should be entered to one of our milestones.

**Comment by lotan1** [comment]
the method looks good.
dont now how complicated is to do,
but the possibility of facebook avatar and manual define avater should be at this week milestone for my opinion.

**Comment by gl1000007** [comment]
What change has been done?

**Comment by lotan1** [comment]
uploading an avatar or using the social network login avatar
