### ISSUE TITLE
User profile editing always annouce אין לך הרשאות עריכה

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#197]
אין לך הרשאות עריכה. כדי לקבל הרשאת עריכה עליך לספק כתובת דואר אלקטרוני חוקית

**Comment by Suberri** [comment]
Just a note - It seems that although the user gets the warning message that you mentioned the user is able to edit/save  the profile.

**Comment by lotan1** [comment]
אכן
its just a note from somthing else that can be removed

**Comment by Suberri** [comment]
Agree

**Comment by daonb** [comment]
I solved the newer issue - #221 .
