### ISSUE TITLE
New Locality Page Design

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#199]
**This issue is now closed, as it split to many small issues.
The team can use this issue as a to-do list: When all the referenced issues are closed, the page should be ready.**
Latest Version can be found [here](https://docs.google.com/document/d/1m-Ztw8dLNA9tYpD3Y3lsW3kcCm3RddnA9BS3G7ZORWA/edit?usp=sharing)

---

https://drive.google.com/folderview?id=0B3yaQaorsX55VWxfU04tOGZGUTg&usp=sharing
More comprehensive explanation will come later today
Update: Spotted some mistakes. It's unavoidable since it's 3:27 AM...

**Comment by lotan1** [comment]
nice!

2013/8/27 Gilad L notifications@github.com

**Comment by daonb** [comment]
I'm working on it.  My only comment is that instead of filtering the
candidates we should be split them into two columns: First those who are
running for mayor and those who running for city council. Have you though
of that?

**Comment by gl1000007** [comment]
Yes I have. There are candidates running for mayor, candidates running for city council, and candidates that running for _both_ - each one of them has 2 notes, one for themselves and one for their list.

P.S.
I messed with the note colors. Candidate note should be yellow, list note should be white.

**Comment by gl1000007** [comment]
I think this page is a duplicate to the "questions" and "answers" page, as it shows all of those pages' content, and can link to individual questions and candidates directly.

Maybe we can use this page **instead** of the current pages.
In this case, I suggest to:
- Make the top bar buttons (home, candidates, questions) lead to in-page bookmarks: 
  - Home - Locality Info ("אא מעלה אבק")
  - Candidates - Candidate list/
  - Questions - Question and tag list.
- Highlight the relevant top-bar button, according to the part the user is currently viewing. something like http://uxonbeer.co.il/ (this is called a "one pager" site).
- Deal with scrolling through questions:
  - Current state is that after 20 questions, users have to click on "forward" button, and on the new page they find themselves at the top of the page, which now has a massive header (Locality info, Candidates info), and lose orientation completely.
  - I thought about 2 solutions, listed according my own personal preference (descending):
  - Make the question list an endless (infinite) scroll page - when users reach the end of the first 20 questions, next 20 are loaded automatically. 
  - Make the next, previous and page number buttons direct to the inner bookmark of the question list in the target page.

If you think like me, comment me and I'll repost this as a new issue(s).

**Comment by gl1000007** [comment]
New version is up, including many minor improvements, but more important - **comprehensive explanation**.
Take a look in [Google Drive](https://docs.google.com/document/d/1m-Ztw8dLNA9tYpD3Y3lsW3kcCm3RddnA9BS3G7ZORWA/edit?usp=sharing)

**Comment by daonb** [comment]
I don't think the navbar with "Questions" and "Candidates" is required anymore and we should remove it.
Let's close this and open three new issues:
- remove the navbar
- Add the locality sumbol and location map
- Replace question pagination with scrolling

**Comment by gl1000007** [comment]
Looking good  :)
But what about "שלומות" and the candidates section?
Candidates section has more details, like filtering, notes, list names and graphical cues.
and "שלומות" can't be seen at all.

what are the plans for these parts?
In case these parts are scheduled to a future due-date, I afraid we forget them and lose track of them.
Should this issue remain open, maybe open separate ones? something else?

**Comment by daonb** [comment]
Better to close this one and open many new small issues. It helps
distrubute the work abd track whats been done. The smaller the issue the
better.

**Comment by gl1000007** [comment]
OK, I think I'm done here.
The team can use this issue as a to-do list: When all the referenced issues are closed, the page should be ready.
Now closing.

**Comment by gl1000007** [comment]
someone please add the small issues to a milestone

**Comment by lotan1** [comment]
I'll try

2013/8/30 Gilad L notifications@github.com

**Comment by gl1000007** [comment]
8 issues are still wide open. enter the issue page to see.
