### ISSUE TITLE
Locality Page - Remove The Navbar

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#202]
Further to https://github.com/hasadna/open-shot/issues/199

I think we can remove the second line of the header completely:
- "questions" and "candidates" are not needed anymore.
- "home" is a duplicate of the logo.
- "about" can remain in its place at the footer.
- language change buttons can be added as a future issue, if we actually have multi language content.
- "# days for election" string can be removed. It's completely optional.

**Comment by lotan1** [comment]
to my opinion municipality home shouldnt hold all the questions and the candidates, just those we want,
so you still might use question full list and candidates list

**Comment by daonb** [comment]
"just those we want" sounds very bad. Either we display all the content or
none of it. I prefer to have a simple layout and just one way to view
content.

**Comment by lotan1** [comment]
We may want to place in the local homepage those candidats who answered more questions or randomly.
As well as we can use the most popular 10 questions and the most last written 5 questions.
Thats insted of placing them all in the same page

**Comment by daonb** [comment]
If we want to change we always can. for now, there's no point in keeping
the navbar

On 28 August 2013 20:10, lotan1 notifications@github.com wrote:

> We may want to place in the local homepage those candidats who answered
> more questions or randomly.
> As well as we can use the most popular 10 questions and the most last
> written 5 questions.
> Thats insted of placing them all in the same page
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/202#issuecomment-23431285
> .

## 

http://yeda.us/daonb

**Comment by gl1000007** [comment]
No, its not. Search bar is still at the second line, interfearing the content area of the page.
Check my wireframe at #199 .
@lotan1 please reopen.

**Comment by tbrisker** [comment]
Keep the nav bar, move the search up to the navbar.
