### ISSUE TITLE
Locality Page - Add a Map View

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#203]
Further to https://github.com/hasadna/open-shot/issues/199
I think we should first try to use [OpenTaba](https://github.com/niryariv/opentaba-server) API, and use Google Maps only as a 2nd option.
More info at [Google Drive](https://docs.google.com/document/d/1m-Ztw8dLNA9tYpD3Y3lsW3kcCm3RddnA9BS3G7ZORWA/edit?usp=sharing)

**Comment by gl1000007** [comment]
new size: 103x103 instead of 142x142.
[Wireframe](http://www.google.com/url?q=https%3A%2F%2Fdocs.google.com%2Ffile%2Fd%2F0B3yaQaorsX55ZVJRd0l3UWV0VjA%2Fedit%3Fusp%3Dsharing)
[Details](https://docs.google.com/document/d/13nz0ByXhC7KsE_S8QklabbTWCHMlopPkfhnKHzcia5I/edit?pli=1#bookmark=id.bya0yqm2i267)

**Comment by tbrisker** [comment]
after discussing this with @gl1000007 , will not fix. users know where their city is, and if they don't know and want to find out they can look it up in google maps on their own.
