### ISSUE TITLE
Locality Page - Add Locality Symbol

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#204]
Further to https://github.com/hasadna/open-shot/issues/199
More info at [Google Drive](https://docs.google.com/document/d/1m-Ztw8dLNA9tYpD3Y3lsW3kcCm3RddnA9BS3G7ZORWA/edit?usp=sharing)

**Comment by lotan1** [comment]
the symbols by municipality nummber are here: 
https://drive.google.com/?tab=mo&authuser=0#folders/0BybPNoUcfXcMekNaODljLVlXelE

**Comment by lotan1** [comment]
can i offer some of my black jobs abilitys on it?

**Comment by gl1000007** [comment]
new size: 103x103 instead of 142x142.
[Wireframe](http://www.google.com/url?q=https%3A%2F%2Fdocs.google.com%2Ffile%2Fd%2F0B3yaQaorsX55ZVJRd0l3UWV0VjA%2Fedit%3Fusp%3Dsharing)
[Details](https://docs.google.com/document/d/13nz0ByXhC7KsE_S8QklabbTWCHMlopPkfhnKHzcia5I/edit?pli=1#bookmark=id.sjm7wvz4ziac)
