### ISSUE TITLE
Support Question on Question List

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#206]
![support question on question list](https://f.cloud.github.com/assets/5072931/1043324/fe913040-0ffb-11e3-8201-b086f543bba5.png)

Related to https://github.com/hasadna/open-shot/issues/153

**Comment by gl1000007** [comment]
updated picture, now added buttons are not adding to the height of the question object.

**Comment by tbrisker** [comment]
duplicate #255

**Comment by gl1000007** [comment]
@tbrisker why duplicate? look at the issue numbers: this one is 206 and the other one is 255.
Anyway, since you have already closed this one, I'll copy the pic to 255.

**Comment by tbrisker** [comment]
I closed this as duplicate because the discussion about it was in 255.
