### ISSUE TITLE
Locality Page - Candidates Section - (1/2) Candidate Widget

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#209]
Further to https://github.com/hasadna/open-shot/issues/199

![zadik](https://f.cloud.github.com/assets/5072931/1044435/a3902690-1011-11e3-9af4-15bc5e4660b4.PNG)

avatar dimensions:140x140
More info at [Google Drive](https://docs.google.com/document/d/1m-Ztw8dLNA9tYpD3Y3lsW3kcCm3RddnA9BS3G7ZORWA/edit?usp=sharing)

**Comment by gl1000007** [comment]
List characters can be added to the name of the list.
exmaple (RTL):
רשימת הצדיקים (צדק)

**Comment by ricardinho** [comment]
Took this. Please assign me :)

**Comment by lotan1** [comment]
explain?

2013/10/7 Ricardo Moreno notifications@github.com

**Comment by ricardinho** [comment]
Working on this issue right now... If you are too then i'll do something else...

**Comment by lotan1** [comment]
good luck!

2013/10/7 Ricardo Moreno notifications@github.com

**Comment by gl1000007** [comment]
Not entirely. #389
