### ISSUE TITLE
Locality Page - "שלומות" Bubble

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#211]
Further to https://github.com/hasadna/open-shot/issues/199

More info at [Google Drive](https://docs.google.com/document/d/1m-Ztw8dLNA9tYpD3Y3lsW3kcCm3RddnA9BS3G7ZORWA/edit?usp=sharing)

**Comment by lotan1** [comment]
else then this new cool feature?

![screenhunter_58 aug 31 12 43](https://f.cloud.github.com/assets/4595165/1062070/cfb0828a-1221-11e3-8622-d55e5380ed23.jpg)

**Comment by gl1000007** [comment]
This cool new feature is based on my design. Haven't you seen the wireframe???
I'm preparing a pic with explaination about what still needs to be done here (let's call it a second iteration). Please don't close.

**Comment by gl1000007** [comment]
OK, "cool-feature" upgrade is ready.
https://docs.google.com/document/d/1m-Ztw8dLNA9tYpD3Y3lsW3kcCm3RddnA9BS3G7ZORWA/edit#bookmark=id.ib3hhka8xz1w

Before realizing this, #202 should be closed.

**Comment by daonb** [comment]
Can we close this?
