### ISSUE TITLE
Locality Page - Locality Statistics

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#212]
![localitystatistics](https://f.cloud.github.com/assets/5072931/1044504/c5152530-1012-11e3-97c8-d79409bf609b.PNG)

Further to https://github.com/hasadna/open-shot/issues/199

Take @daonb's excellent work ([example](http://localshot.org.il/97/qna/)) and append to it the data which presented in this picture.
Comprehensive explanation about data sources and calculating method for response percentage, can be found on [Google Drive](https://docs.google.com/document/d/1m-Ztw8dLNA9tYpD3Y3lsW3kcCm3RddnA9BS3G7ZORWA/edit?usp=sharing)
If the result takes too much vertical space (higher than the [map](https://github.com/hasadna/open-shot/issues/203) or [locality symbol](https://github.com/hasadna/open-shot/issues/204)), you can reformat the content as a single long line, comma separated.

**Comment by daonb** [comment]
The reason the change was reverted is because google drive performance was slowing the entire site down. 
The things to do are:
- edit the [spreadsheet](https://docs.google.com/spreadsheet/ccc?key=0AibPNoUcfXcMdDJfTWlQTG1lcUFtOTgydTJldWRPMnc&usp=sharing) to have english coloumn label
- download it as csv and write a small script to turn it into a json object where the locality code is used as an index
- save the json file in static/js/entity_stats.js and use it in the `question_list.html` template

**Comment by lotan1** [comment]
Can we use the "all in one" spreadsheet?
https://docs.google.com/spreadsheet/ccc?key=0AibPNoUcfXcMdHFrSmlOc1plZTA5Y1dGWjc1ZXh3Y3c#gid=0
I copied the english label (some) from open muni budget

2013/9/2 benny daon notifications@github.com

**Comment by daonb** [comment]
Sure, use lotan's spreadsheet

**Comment by tbrisker** [comment]
i'm on it

**Comment by tbrisker** [comment]
what information should we display on the locality? population? number of council members? socio-economic cluster? something else?

**Comment by lotan1** [comment]
great
those, and maybe we shell use allowd voters(בזב"ים) if they will publish.
my next options are: 
מאזן הגירה (סהכ נכנסים-סהכ יוצאים) , סה"כ הוצאות הרשות, גרעון מצטבר, ואז קצת נתוני חינוך
can we use just few indicators and add "click here for more" thing?
its not our goal but a nice feature.

**Comment by gl1000007** [comment]
לא ניסחתי את זה מספיק ברור? יש למעלה איור מאוד מדויק, וגם קישור לגוגל דרייב. פשוט תקראו את ההודעה שפתחה את הדיון הזה. בבקשה להתחיל מהנתונים שכתבתי, ואח״כ אפשר להוסיף את מה שכתבתם ב-2 ההערות האחרונות.

**Comment by daonb** [comment]
First version didn't look good enough. Bug is at #246
