### ISSUE TITLE
the name tag of the questioners looks bit unnecessary beside the avatars

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#214]
any way most of the users and candidates dosnt know the questioners,
and if they do they will recognize their pictures.
Dont know, somthing about the design of the questions view dosnt look good.
Take a look here:
![screenhunter_58 aug 29 00 48](https://f.cloud.github.com/assets/4595165/1045832/109d1774-102c-11e3-9b09-7ea3e7124b29.jpg)

**Comment by danielhers** [comment]
How about showing it under the avatar, like in the candidate names?

**Comment by lotan1** [comment]
could be better.
but its not for now anyway
lets finsh the candidate issues

**Comment by danielhers** [comment]
@gl1000007 what do you suggest?

**Comment by gl1000007** [comment]
@lotan1  can you be more specific? "something" doesn't tell me anything.
Until then, I suggest to **do nothing**. Yes do nothing at all.
The name is used to identify the person in a more unique manner, so it has to stay.
Really, this is a tiny bit and we are short in time. What about the big picture? There are many features we have not begun to apply (!)
Please close.
