### ISSUE TITLE
Rearrange tags list

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#215]
Tags sorted now alphabetic,
shuld be by nummbers (of tag uses that appears already).
or somthing more sophisticated as cloud by size etc

**Comment by gl1000007** [comment]
Tag sorting and font sizing by uses are good ideas :)
Please open 2 separate issues for these, link them to this issue, and then close this one (like I did in https://github.com/hasadna/open-shot/issues/199).

(Damn you mobile Safari! Now I have to write this comment all over again!)

**Comment by lotan1** [comment]
forget about the size and cluod
lets go with sorting

2013/8/29 Gilad L notifications@github.com

**Comment by gl1000007** [comment]
Why forget?
Maybe it isn't in top priority right now, but we can get to it later.
Just open an issue(s) and it would wait for us, not interfearing in any way.

Sent from my iPhone 5S

ב-29 באוג 2013, בשעה 13:03, lotan1 notifications@github.com כתב/ה:

**Comment by daonb** [comment]
I feel there's a deeper question here we should consider. I feel the using larger fonts for more popular tags and sorting them according to poppularity is wrong because the more popular tags are not the more important tags.
If you want to convince me, you'll need a better reason than "it's a good idea" and some samples...

**Comment by lotan1** [comment]
more reasons are, the unxplain order that is now:
![screenhunter_58 sep 01 09 33](https://f.cloud.github.com/assets/4595165/1063598/7fad9124-12d0-11e3-9d32-91e6df4c891f.jpg)
and take a look at maale avavk to see what alphabetic order will look like on the first screen.
order by popularity can show an active site

**Comment by daonb** [comment]
So lets order it from a to z

**Comment by lotan1** [comment]
I think that if someone would search somthing he can use the search.
and mabye I didnt understand the the purpose of viewing tags
anyway now I thinkl its not so good
![screenhunter_59 sep 01 22 14](https://f.cloud.github.com/assets/4595165/1064551/e76b96e8-133a-11e3-8e88-bb7247458145.jpg)

**Comment by daonb** [comment]
Well, until someone has a better idea, this is fixed as the order is alphabetic
