### ISSUE TITLE
New municipality welcome message "about" link is broken

### ISSUE THREAD

**Issue by danielhers** [hasadna/open-shot#216]
For example, in http://localshot.org.il/268/qna/ the "about" link points to http://localshot.org.il/about where it should be http://localshot.org.il/p/about/

**Comment by daonb** [comment]
Just tested, seems like the problem is with the 'About' link on the welcome messages, which can be changed through the admin panel. Which reminds me, lotan give daniel superuser access so next time he can fix it himslef and save us two days!

**Comment by lotan1** [comment]
done

2013/8/31 benny daon notifications@github.com

**Comment by danielhers** [comment]
When I go to http://localshot.org.il/admin/ I get Server Error (500)

**Comment by daonb** [comment]
I'm on it

On 1 September 2013 11:40, Daniel Hershcovich notifications@github.comwrote:

> When I go to http://localshot.org.il/admin/ I get Server Error (500)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/216#issuecomment-23621033
> .

## 

http://yeda.us/daonb

**Comment by danielhers** [comment]
Looks good
