### ISSUE TITLE
Firefox has blocked content that isn't secure

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#217]
![contentnotsecure](https://f.cloud.github.com/assets/5072931/1051210/bc744258-10c6-11e3-945e-8e06490c32cb.png)

Firefox 23.0.1

**Comment by lotan1** [comment]
I Dont know anything about it, but I have this plugin at firefox
www.webutation.net says we are at 70/100

2013/8/29 Gilad L notifications@github.com

**Comment by daonb** [comment]
I'm on 23.0 and I don't see it.
