### ISSUE TITLE
server eror during manual registeration process

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#220]
on successful login you'll get Server Error (500)
![screenhunter_58 aug 31 14 13](https://f.cloud.github.com/assets/4595165/1062182/dc6a887e-122e-11e3-9999-72ae6d09b69a.jpg)

**Comment by daonb** [comment]
Doesn't look like an error...

**Comment by lotan1** [comment]
the screenshot?
ill take the next screen
here:
![screenhunter_58 aug 31 22 35](https://f.cloud.github.com/assets/4595165/1062901/9b81f1d0-1274-11e3-8432-585da0b2a0e2.jpg)
