### ISSUE TITLE
Feed link is broken

### ISSUE THREAD

**Issue by daonb** [hasadna/open-shot#226]
Clicking the rss icon on any locality gets you an error

**Comment by lotan1** [comment]
I think its still broken http://localshot.org.il/33/atom/

**Comment by daonb** [comment]
Looking good. you just need a reader. try using feedly.com

**Comment by lotan1** [comment]
ברור
חשבתי שצריך להיות שם איזה מסך הסבר/מעבר
בכל מקרה אני כבר משתדל לא לבדוק את המערכת כל יום אלא לקבל באגים ממשתמשים, זה אחד שכזה
מניח שזה לא המשתמש היחיד שאין לו תוכנה ולא סגור על פישרו של הסמל

**Comment by daonb** [comment]
ככה זה עובד באינטרנט - סמל של פיד שמקשר לפיד. יש גם משתמשים נודניקים...
