### ISSUE TITLE
Fix automatic redirections

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#230]
When and where to automatically redirect a user to another page:
- After login or registration **only**, take the user to their locality.
- When entering to the main page http://localshot.org.il either by typing the URL or by clicking on the logo, display "אא מעלה אבק" for the beta and http://localshot.org.il/ for release.
- For all other pages, just display that page _without any redirections_.

---

copied from [this specific comment](https://github.com/hasadna/open-shot/issues/152#issuecomment-23547668).
This is a follow-up to #152. To any question, and I mean **ANY** question, please take 5 and read it entirely. It is very comprehensive and will take less time than posting a question here, so use it as your first option.

**Comment by lotan1** [comment]
completing registration now lead to the profile without a clear link to your locality qna
![screenhunter_62 sep 03 22 54](https://f.cloud.github.com/assets/4595165/1075684/094f47a2-14d3-11e3-8241-68e5cb8df198.jpg)

**Comment by gl1000007** [comment]
At the last meeting we found a solution for that.
I'll update everything shortly.

**Comment by gl1000007** [comment]
Closed as outdated. Read this specific comment in https://github.com/hasadna/open-shot/issues/152?source=cc#issuecomment-24050821
Regarding @lotan1 's comment, I've opened a new issue for that. Take a look at #254.
