### ISSUE TITLE
עימודים שמציקים בעין

### ISSUE THREAD

**Issue by polinas123** [hasadna/open-shot#234]
בחלק מהמקומות תגיות מתחיל בשול הימני מתחת לתמונת הפרופיל, בחלק מהמקומות יש הזחה לשמאל ככה שזה מופיע מתחת לטקסט. כדאי ליישר באופן אחיד לאחת מהאופציות

כותרות ארוכות שנשברות לשתי שורות נראות קרובות מדי לריבוע הכחול של שם המשתמש - מציעה להכניס הזחה או להגדיל את הרווח בין השורות

הכוונה לעמוד הזה למשל
http://localshot.org.il/277/qna/

**Comment by tbrisker** [comment]
I believe this is fixed now, if not please provide a screenshot.
