### ISSUE TITLE
Bug - was able to delete a question that I did not author

### ISSUE THREAD

**Issue by Suberri** [hasadna/open-shot#235]

**Comment by danielhers** [comment]
Are you an editor in the question's locality?

**Comment by lotan1** [comment]
Didnt find it

**Comment by Suberri** [comment]
mmm...
I think so. When I signed up I was informed that I am the first person in
Modiin, and thus the system choose me to be an editor.

On Mon, Sep 9, 2013 at 8:29 AM, Daniel Hershcovich <notifications@github.com

> wrote:
> 
> Are you an editor in the question's locality?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/235#issuecomment-24042748
> .

## 

Cheers
Moshe

**Comment by danielhers** [comment]
Editors can delete questions in their localities by design.

**Comment by Suberri** [comment]
yes you r correct

On Mon, Sep 9, 2013 at 1:12 PM, Daniel Hershcovich <notifications@github.com

> wrote:
> 
> Editors can delete questions in their localities by design.
> On Sep 9, 2013 1:09 PM, "Suberri" notifications@github.com wrote:
> 
> > mmm...
> > I think so. When I signed up I was informed that I am the first person
> > in
> > Modiin, and thus the system choose me to be an editor.
> > 
> > On Mon, Sep 9, 2013 at 8:29 AM, Daniel Hershcovich <
> > notifications@github.com
> > 
> > > wrote:
> > > 
> > > Are you an editor in the question's locality?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/hasadna/open-shot/issues/235#issuecomment-24042748>
> > > .
> > 
> > ## 
> > 
> > Cheers
> > Moshe
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/hasadna/open-shot/issues/235#issuecomment-24059483>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/235#issuecomment-24060043
> .

## 

Cheers
Moshe
