### ISSUE TITLE
How can one find if he supported a question?

### ISSUE THREAD

**Issue by Suberri** [hasadna/open-shot#236]

**Comment by gl1000007** [comment]
1. #153 
2. In the user page, there will be a list of supported questions.
   There is nothing to do here, please close.

**Comment by Suberri** [comment]
GL,

Thanks.
Went to my page (the menu item under my name) and could not find the
question that I have supported.

Cheers
M

On Mon, Sep 2, 2013 at 3:21 PM, Gilad L notifications@github.com wrote:

> 1. #153 https://github.com/hasadna/open-shot/issues/153
> 2. In the user page, there will be a list of supported questions.
>    There is nothing to do here, please close.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/236#issuecomment-23657081
> .

## 

Cheers
Moshe
