### ISSUE TITLE
support hebrew user names

### ISSUE THREAD

**Issue by daonb** [hasadna/open-shot#24]
Because it's ugly to mix two languages

**Comment by yaninelbi** [comment]
+1

**Comment by daonb** [comment]
I know you can use _edit prfile_  your name to be in hebrew

**Comment by david206** [comment]
1. בחירת שם משתמש: הכנסתי את שמי המלא - וקיבלתי תשובה: ערך זה יכול להכיל אותיות, ספרות והתווים @/./+/-/_ בלבד. הכנסתי את שמי הפרטי (אותיות בלבד), וקיבלתי את אותה התשובה. מניח שהכוונה היא שהערך יכול לקבל אותיות באנגלית בלבד - כדאי להסביר.
