### ISSUE TITLE
Find a way to group candidates in the locality page

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#240]
copied from a mail from polina s:
מה קורה אם יש הרבה רשימות, ונגיד לכל רשימה שישה מועמדים? אז בעמוד העירוני יש מלא מלא מועמדים
גם אם מסווגים אותם לפי לבן וצהוב - עדיין יש בליל של מועמדים (בערים הגדולות לפחות) איך מסדרים את זה? אולי איזשהו סוג של קיבוץ (עיגולים שקצת עולים אחד על השני לפי סדר הרשימה וככה יותר קל לקלוט בעין שזו רשימה נפרדת מהאחרות, וככה רק ראש הרשימה במוקד

This is not an urgent task, but its here for us to not forget it. please assign it to a milestone.

---

a few possible ideas:
use an inline frame with a scrollbar
group with a circle like the android home screen

**Comment by lotan1** [comment]
maybe we can use on the form of candidate registration, a required field of party letter, and of place in the list.
then view on the city page just the head of each party (5-25 for desgin).
and to make it possible to open evry party list as if it was list of questions realted to a tag.

**Comment by lotan1** [comment]
#210 , #209, #126 
temporary fix can be: display on locality page only mayor candidates, and municipality lists.
display them in two separate slots orderd by answers 
anyway its should changed soon

**Comment by tbrisker** [comment]
how should we display the lists, as they have no avatar (and as they can upload any image they want, we can't simply use their image as it won't be a fixed size)?

**Comment by lotan1** [comment]
their white letters voting note?

**Comment by gl1000007** [comment]
![240 group candidates](https://f.cloud.github.com/assets/5072931/1233802/52f27422-2943-11e3-8843-d72c564558ff.PNG)
At the left, user can select a list and filter by that. Default is "All the lists", which is not shown here.
At the top-right, user can filter by candidate type: mayor, city council or no filter.
Both of the filtering options take action simultaneously.
What do you think?

**Comment by tbrisker** [comment]
take into account that in some localities there may be over 100 council candidates.
i think that at first we should only show mayor candidates and lists and add filtering later - but the layout looks good.

**Comment by gl1000007** [comment]
How about adding an Expand button, that expands the layout to fill all of the vertical space in the viewport (minus the height of the button itself)?

**Comment by gl1000007** [comment]
Updating the [Spec](https://docs.google.com/document/d/1cEObTn5NWn-BjkWpSiqpsmy8zCMGVmmt4h9rv8XaRnE/edit?usp=sharing) now.

**Comment by gl1000007** [comment]
![dei85yt8goig](https://f.cloud.github.com/assets/5072931/1238599/8756a23a-29eb-11e3-9358-951bee17d530.PNG)
Updated. [Read sections 6-11](https://docs.google.com/document/d/1cEObTn5NWn-BjkWpSiqpsmy8zCMGVmmt4h9rv8XaRnE/edit#bookmark=id.c49yn9o2yab4).
**Now closing, because this issue consists of several sub-issues, which will be opened separately.**
This issue will remain for reference.
