### ISSUE TITLE
Server Error 500 when posting a question

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#243]
http://localshot.org.il/qna/post_q/

**Comment by lotan1** [comment]
actually it happans evrywere
http://localshot.org.il/%D7%91%D7%90%D7%A8-%D7%A9%D7%91%D7%A2-2/qna/%D7%9E%D7%94%D7%95-%D7%A9%D7%99%D7%AA%D7%95%D7%A3-%D7%A6%D7%99%D7%91%D7%95%D7%A8-%D7%91%D7%A2%D7%99%D7%A0%D7%99%D7%9A-%D7%95%D7%94%D7%90%D7%9D-%D7%95%D7%9B%D7%99%D7%A6%D7%93-%D7%94%D7%95%D7%90-%D7%A6%D7%A8%D7%99%D7%9A-%D7%9C%D7%94%D7%AA%D7%A8%D7%97%D7%A9-%D7%91%D7%A2%D7%99%D7%A8-%D7%A9%D7%9C%D7%A0%D7%95/
http://localshot.org.il/%D7%90%D7%90-%D7%9E%D7%A2%D7%9C%D7%94-%D7%90%D7%91%D7%A7/qna/%D7%9B%D7%99%D7%A6%D7%93-%D7%91%D7%9B%D7%95%D7%95%D7%A0%D7%AA%D7%9B%D7%9D-%D7%9C%D7%A4%D7%AA%D7%97-%D7%90%D7%AA-%D7%94%D7%AA%D7%97%D7%91%D7%95%D7%A8%D7%94-%D7%94%D7%A6%D7%99%D7%91%D7%95%D7%A8%D7%99%D7%AA-%D7%91%D7%A2%D7%99%D7%A8-%D7%9E%D7%91%D7%97%D7%99%D7%A0%D7%AA-%D7%94%D7%99%D7%A7%D7%A4%D7%94-%D7%90%D7%99%D7%9B%D7%95%D7%AA%D7%94-%D7%95%D7%96%D7%9E%D7%99%D7%A0%D7%95%D7%AA%D7%94/

**Comment by daonb** [comment]
couldn't recreate. can you try again with different types of users?

**Comment by lotan1** [comment]
Half of the questions here: http://localshot.org.il/33/qna/
But maybe its all becuase of the same question title bug #244

**Comment by tbrisker** [comment]
couldn't recreate. reopen if happens again.
