### ISSUE TITLE
Tags for deleted questions are still displayed in the locality page

### ISSUE THREAD

**Issue by danielhers** [hasadna/open-shot#245]
![selection_036](https://f.cloud.github.com/assets/263363/1087065/a4323d34-160d-11e3-8b84-5142d8ac1b2e.png)

**Comment by danielhers** [comment]
This is a follow-up on #171 .

**Comment by daonb** [comment]
I guess before deleting a question we should [clear](https://django-taggit.readthedocs.org/en/latest/api.html#TaggableManager.clear) its tags.
