### ISSUE TITLE
Questions edit Not Found

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#247]
Not Found

The requested URL /אא-מעלה-אבק/qna/מהו-שיתוף-ציבור-בעיניך-וכיצד-הוא-צריך-להתרחש-בעיר-שלנו/edit/ was not found on this server.

http://localshot.org.il/%D7%90%D7%90-%D7%9E%D7%A2%D7%9C%D7%94-%D7%90%D7%91%D7%A7/qna/%D7%9E%D7%94%D7%95-%D7%A9%D7%99%D7%AA%D7%95%D7%A3-%D7%A6%D7%99%D7%91%D7%95%D7%A8-%D7%91%D7%A2%D7%99%D7%A0%D7%99%D7%9A-%D7%95%D7%9B%D7%99%D7%A6%D7%93-%D7%94%D7%95%D7%90-%D7%A6%D7%A8%D7%99%D7%9A-%D7%9C%D7%94%D7%AA%D7%A8%D7%97%D7%A9-%D7%91%D7%A2%D7%99%D7%A8-%D7%A9%D7%9C%D7%A0%D7%95/edit/

**Comment by daonb** [comment]
I'm assuming you logged in as the author of the question, got in its [page](http://localshot.org.il/%D7%90%D7%90-%D7%9E%D7%A2%D7%9C%D7%94-%D7%90%D7%91%D7%A7/qna/%D7%9E%D7%94%D7%95-%D7%A9%D7%99%D7%AA%D7%95%D7%A3-%D7%A6%D7%99%D7%91%D7%95%D7%A8-%D7%91%D7%A2%D7%99%D7%A0%D7%99%D7%9A-%D7%95%D7%9B%D7%99%D7%A6%D7%93-%D7%94%D7%95%D7%90-%D7%A6%D7%A8%D7%99%D7%9A-%D7%9C%D7%94%D7%AA%D7%A8%D7%97%D7%A9-%D7%91%D7%A2%D7%99%D7%A8-%D7%A9%D7%9C%D7%A0%D7%95/) and then clicked the edit button to get the error. right?

**Comment by lotan1** [comment]
Right.

2013/9/9 benny daon notifications@github.com
