### ISSUE TITLE
Create some admin statistics 

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#250]
For example,
no' of questions/users/candidates/active localities
arranged by date/locality/users etc.

**Comment by daonb** [comment]
For now, the best way will be to use analytics to track the activity.
Theres a way to add goals and track them of time. Analytics will not only
tell us how man users registeted, joined a q, etc but will also give us
conversion rates

**Comment by lotan1** [comment]
or manualy:
local editors: name, mail, fb, locality
active localities: users no', questions no', ansaers no'

**Comment by tbrisker** [comment]
todo: fix editor count to be correct, add answer and candidate count.
