### ISSUE TITLE
Completing registraion should lead to the user's locality page

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#254]
Further to @lotan1 's comment in https://github.com/hasadna/open-shot/issues/230#issuecomment-23742146 (no need to enter, as it's summarized below)

Copied from 230:
completing registration now lead to the profile without a clear link to your locality qna
![094f47a2-14d3-11e3-8241-68e5cb8df198](https://f.cloud.github.com/assets/5072931/1105425/008b5ee2-1926-11e3-8586-40e57873b082.jpg)

Like Lotan, I find no sense in redirecting a new user to their empty profile page,
so the action item is - make the redirection lead to the user's locality page, enabling them to post and support questions immediately.

**Comment by daonb** [comment]
I think the user should see his page. It's the decent think to do - if we create a page and we link to it from other pages it makes sense the user should be the first to see his page. 
BTW - I'm not sure when you took the screenshot, but now it looks more like below, so it's easy to get to the user's locality:

![image](https://f.cloud.github.com/assets/36852/1106455/3175b1b4-1945-11e3-91f9-dd6999ec9b24.png)
