### ISSUE TITLE
Clicking on 'Candidate' and the 'Home' stays selected

### ISSUE THREAD

**Issue by daonb** [hasadna/open-shot#26]

**Comment by yaninelbi** [comment]
That is correct, can you add a view variable containing the active menu context ? (page/controller?)

**Comment by daonb** [comment]
I think that when I'm on questions page I should have no navbar item selected

**Comment by yaninelbi** [comment]
I think that we should update the "Home" button to say "Questions" and that should be selected, so it's a clear.
I believe that in the near future the home page wouldn't only contain the questions but only the top ones / newest as opposed to containing all of them as it is now. That's when a questions section would be appropriate (that would show all questions). I'll remove it for now then
