### ISSUE TITLE
Shuld we delete entities that wont ellect?

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#262]
Its minoric issue, less then 50 entities seems to not paricipating the next ellection
http://bocharim.org.il/files/list.pdf

**Comment by lotan1** [comment]
we can delete the regional entities as well, arnt usful anyway

**Comment by tbrisker** [comment]
entities that are up for election are these: http://bocharim.org.il/files/list.pdf

**Comment by tbrisker** [comment]
@daonb  - would deleting entities from the DB cause any problems? what about the regional entities?

**Comment by tbrisker** [comment]
also regional councils that are up for elections : http://bocharim.org.il/#idBchirotLamoazot (not in the pdf)

**Comment by lotan1** [comment]
maybe just hide those that wont ellect as done with regions
I can create the XLS of localities 1/0 for participating and updated
nummber of seats

2013/10/2 tbrisker notifications@github.com

**Comment by lotan1** [comment]
quick solution can be remove view of entities without candidates

**Comment by lotan1** [comment]
should be simple isnt it?
if we do have now on db regional entities that wont show on site and appear at admin,
why wont we do the same with מועצות אזוריות
or make an if for more than 1 candidate at municipality

**Comment by daonb** [comment]
we just need to make sure we delete the fixture/initial_data.json or
deleted entity we reappear when we upgrade

On 16 October 2013 12:34, lotan1 notifications@github.com wrote:

> should be simple isnt it?
> if we do have now on db regional entities that wont show on site and
> appear at admin,
> why wont we do the same with מועצות אזוריות
> or make an if for more than 1 candidate at municipality
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/262#issuecomment-26407546
> .

## 

http://yeda.us/daonb

**Comment by lotan1** [comment]
since we havnt delete the entity "הדרום" I just thoght why wond we do the
same with "אבו בסמה"?
but ill leave it here for you

2013/10/16 benny daon notifications@github.com

> ed to make sure we delete the fixture/initial_data.json or
> deleted entity we reappear
