### ISSUE TITLE
Add back to locality button on question detail page.

### ISSUE THREAD

**Issue by nogar** [hasadna/open-shot#266]
אחרי פרסום שאלה צריך כפתור שיחזיר אותי לעמוד העיריה שלי

**Comment by nogar** [comment]
הייתי שוקלת לעשות מיון לפי נושאים, כלומר כאשר מעלים שאלה יש לבחור לה נושא ראשי: חינוך, בינוי, מיסים, פוליטיקה וכו׳.
הייתי שמחה לראות חלוקה לפי אשכולות המידע האלה וככה זה גם ימנע הרבה שאלות חוזרות.....

**Comment by tbrisker** [comment]
לגבי החלוקה לנושאים - בשביל זה יש תגיות, לא יהיה תמיכה מעבר לכך בשלב הזה.

**Comment by gl1000007** [comment]
לגבי העברה לעמוד העיריה, זה יעבוד רק אם תצוגת ברירת המחדל תהיה של השאלות האחרונות. טענה זו מתבססת על ההנחה שהמשתמש ירצה לראות את השאלה שלו מופיעה בפועל באתר, בתור אישור לזה שהשאלה פורסמה בהצלחה. אם אני זוכר נכון (#251), אנחנו לא הולכים לכיוון של שאלות אחרונות אלא של _שאלות מובילות_, ולכן עדיף להשאיר את המצב הקיים - להפנות אל דף השאלה אפילו שאין בו תשובות.
עוד דבר - משתמשים מתקדמים ירצו לשתף את השאלה שלהם ברשתות החברתיות ובאתרים אחרים. אם אנחנו מעבירים אותם ישירות לדף של השאלה שלהם, הם יכולים מיד להעתיק את הכתובת ולשתף. אם נעביר לכל דף אחר, אנחנו סתם מקשים עליהם וזה מוריד מהויראליות של האתר.

**Comment by tbrisker** [comment]
@gl1000007  - if I understand correctly the idea is just to add a button below the question to go back to the locality page (right now the user has to guess that to get back they need to click on the logo in the menu bar)
