### ISSUE TITLE
Update the numbers of municipality seats

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#267]
current is the Lamas numbes by the last ellections
Where should I correct it? on the drive?

**Comment by tbrisker** [comment]
There are changes? i pulled the stats from the lamas file you put on the drive. 
If there are only few changes it might be faster to manually edit the stats in the project, otherwise update the file on the drive and let me know once it's updated so I can scrape it again.

**Comment by tbrisker** [comment]
The updated list is here: http://bocharim.org.il/files/list.pdf, we need to update the [cbs file](https://docs.google.com/spreadsheet/ccc?key=0AibPNoUcfXcMdHFrSmlOc1plZTA5Y1dGWjc1ZXh3Y3c&usp=drive_web) on the drive and scrape it again.

**Comment by gl1000007** [comment]
Looks like it's updated. @lotan1 Close?

**Comment by lotan1** [comment]
I havnet update yet

2013/10/11 Gilad L notifications@github.com

**Comment by lotan1** [comment]
done with https://docs.google.com/spreadsheet/ccc?key=0AibPNoUcfXcMdHFrSmlOc1plZTA5Y1dGWjc1ZXh3Y3c&usp=drive_web#gid=0

**Comment by tbrisker** [comment]
updated on the server.
