### ISSUE TITLE
Add a sitemap for search bots 

### ISSUE THREAD

**Issue by daonb** [hasadna/open-shot#28]

**Comment by pwalsh** [comment]
Hey Benny,

I'd like to do an SEO feature branch to improve the whole searchability of the QA site(s).

That would mean:
- Sitemap
- Good impl of meta tags
- Slugification of Hebrew Qs

The last one will maybe get some resistance so I wanted to check what you say. It will def. be better for search discovery of the QA sites. I have a good impl for this that I have used on another Hebrew site we'll be launching soon. I am using Mozilla's unicode-slugify - they wrote it to address the same problem on their Django sites.

If I open up such a branch, I'll probably find other on-page optimizations for SEO too.

What do you say?

**Comment by daonb** [comment]
Go for it. Regarding hebrew slugification we now use ids as slugs and if
you think we should do it open an issue. I'll add you to the Team next time
i have my laptop connected

**Comment by pwalsh** [comment]
I think it should be done for all public URLs. I'll open an issue for that separately.

**Comment by pwalsh** [comment]
Sitemaps:

I need to understand about the users.
- As I see it there are multiple user types, probably filterable via groups association.

Two two types I can gather from the code are "candidates" and "members".

Do both user types have publicly accessible profile pages, even if they are not implemented yet?

Just working out what else I need for the sitemaps, apart from question paths.

**Comment by daonb** [comment]
For now, we should make sure that users of the `candidates` group pages are
indexed.

**Comment by pwalsh** [comment]
benny you can close this issue.
