### ISSUE TITLE
tag filtering does not work correctly

### ISSUE THREAD

**Issue by tbrisker** [hasadna/open-shot#286]
try for example "אוויר נקי" in maale avak.

**Comment by lotan1** [comment]
its only two word tag problem right? I think its the dash, for example http://localshot.org.il/277/qna/tags/%D7%90%D7%95%D7%95%D7%99%D7%A8-%D7%A0%D7%A7%D7%99/ VS http://localshot.org.il/277/qna/tags/%D7%90%D7%95%D7%95%D7%99%D7%A8%20%D7%A0%D7%A7%D7%99/

**Comment by tbrisker** [comment]
some links still use tag.slug and some use tag(.name) - so now clicking on a link that uses tag name (like the tags on a specific question) doesn't work. 
should be consistent - preferably always using slug in the urls and displaying name in the page.

**Comment by danielhers** [comment]
I'll do that.
