### ISSUE TITLE
In בנימינה-גבעת עדה there are 11 seats, and not 9 like mentioned

### ISSUE THREAD

**Issue by david206** [hasadna/open-shot#288]
See: http://bocharim.org.il/files/list.pdf

**Comment by lotan1** [comment]
yep  #267 it is

**Comment by david206** [comment]
Sorry, didn't understand what I should do.
If I should change a doc, can you please share the link?

Thanks

**Comment by lotan1** [comment]
would you like to update all this list by the new nummbers?
https://docs.google.com/spreadsheet/ccc?key=0AibPNoUcfXcMdHFrSmlOc1plZTA5Y1dGWjc1ZXh3Y3c&usp=drive_web
(E)

**Comment by david206** [comment]
I can't edit this doc.
Anyway, E47 should be 11.
My suggest: Hide this field until it will be fixed.

**Comment by lotan1** [comment]
most of the municipalities are correct, some staged up since 2011
if you can check them all in the open link
https://docs.google.com/spreadsheet/ccc?key=0AibPNoUcfXcMdHFrSmlOc1plZTA5Y1dGWjc1ZXh3Y3c&usp=sharing
it'll help

2013/9/25 david206 notifications@github.com
