### ISSUE TITLE
on ניהול רשימות allow soft delete

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#289]
Now when local admin can add list and candidates, they should handle themself on wrong user pick (easy mistake) or wrong list connect, only if its soft delete
http://oshot.hasadna.org.il/po/list/

**Comment by tbrisker** [comment]
#302

**Comment by tbrisker** [comment]
Candidate removal is now supported for editors, as well as editing lists. 
Deleting will not be supported for editors right now. 
if absolutely necessary, a super user can delete after verifying that there are no candidates in the list.
