### ISSUE TITLE
תלונות מהשטח - מועמד בפ"ת רמי גרינברג מתלונן שנמחקים לו הפרטים בעמוד

### ISSUE THREAD

**Issue by polinas123** [hasadna/open-shot#292]
אני רואה שהמשתמש שלו קיים ואפילו מוצג, מסומן כ is candidate
ניסיתי לשנות דרך users 
משהו פשוט כדי לראות אם זה נשמר וקיבלתי שגיאה על שם משתמש לא חוקי - רמיגרינברג
אולי כי הוא בעברית?

הוא טוען שנרשם דרך הפייסבוק
הוא כנראה סימן שהוא מועמד ורץ מטעם הליכוד

בעיות:
יש את העניין שהוא מוצג כמועמד למועצת העיר ולא לראשות העיר
עניין מחיקת הפרטים, שלא הצלחתי לשחזר בעצמי 

זה המייל שלו rami.greenberg78@gmail.com
זה הציטט שלו

הפרטים שלי נמחקים כל הזמן, בכל הפעלה - נרשמתי דרך פייסבוק ורשמו אותי כמועמד, ואני צריך לכתוב אותם מחדש.
אני רוצה להירשם כמועמד לראשות העיר בפתח תקווה ולא רק כראש הרשימה.
אין לכם פונקציה כזאת לצערי וזה בעייתי.

**Comment by polinas123** [comment]
זו הכתובת של המשתמש שהוא פתח ואני ניסיתי לשנות בו את הביו ואת המין וקיבלתי הודעה על שם משתמש לא חוקי
http://localshot.org.il/admin/auth/user/279/

**Comment by lotan1** [comment]
לפחות הוא עדיין מופיע כמועמד
אני לא רואה טעם למלא פרטים עד שנוכל לקלוט את הפרטים האלו מופרדים לתאים
שונים, כולה פיסקת טקסט בלי קישורים. עדיף להתמקד בתשובות בנתיים

בתאריך 24 בספטמבר 2013 18:08, מאת polinas123 notifications@github.com:

**Comment by polinas123** [comment]
בפ"ת ספציפית יש 4 שאלות כרגע...
תומר ביקש שאפתח, זה מתקדם לשלב שאנחנו נמצאים בו אבל אני רוצה לשמור על
המועמד שלא יברח.
אם יהיה מסובך מדי אמצא דרך להסביר לו שיתחיל עם תשובות... אני קצת בספק שירצה
לעשות את זה כל עוד הוא מופיע כמועמד למועצת העירייה.... לא כל כך טוב לאגו.
חוצמזה אם אנחנו רושמים היום-מחר הרבה מועמדים והעורכים מתחילם לפנות אליהם -
הרי אמרנו שתמריץ טוב זה לתת למועמדים עמודים לא מלאים על עצמם ושיעדכנו - קצת
בעיה אם הם לא יוכלו לעשות את זה. צריך לזכור שהאינטרס של המועמד זה לא לעזור
לאתר להתקדם אלא לקדם את עצמם... אם משהו יראה להם לא מספיק מלא או בעייתי הם
יוותרו. אני הייתי מוותרת בשלב כזה, כשזה עוד לא נראה מספיק מרשים ואין תחרות
בין המועמדים. אם הוא כבר נכנס בעצמו וניסה... כך או כך אני חושבת שזה יזרז
אותנו לתת פתרונות שממילא צריכים להינתן השבוע, לא?

בתאריך 24 בספטמבר 2013 18:17, מאת lotan1 notifications@github.com:

> לפחות הוא עדיין מופיע כמועמד
> אני לא רואה טעם למלא פרטים עד שנוכל לקלוט את הפרטים האלו מופרדים לתאים
> שונים, כולה פיסקת טקסט בלי קישורים. עדיף להתמקד בתשובות בנתיים
> 
> בתאריך 24 בספטמבר 2013 18:08, מאת polinas123 notifications@github.com:
> 
> > זו הכתובת של המשתמש שהוא פתח ואני ניסיתי לשנות בו את הביו ואת המין
> > וקיבלתי
> > הודעה על שם משתמש לא חוקי
> > http://localshot.org.il/admin/auth/user/279/
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/hasadna/open-shot/issues/292#issuecomment-25013219>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/292#issuecomment-25013984
> .

## 

localshot.org.il _השו"ת המקומי_
_אתר שאלות ותשובות לבחירות המקומיות_
בואו. שאלו. השפיעו

**Comment by tbrisker** [comment]
#302

**Comment by tbrisker** [comment]
עדכנתי ידנית אותו כמועמד לראשות העיר ואת המגדר שלו לזכר.
נראה לי שבעיית שמירת הנתונים אולי קשורה ל #307 שנפתר - אנא בקשי ממנו לנסות לעדכן שוב את הפרטים עכשיו.
