### ISSUE TITLE
avatar URL present but no picture appears

### ISSUE THREAD

**Issue by polinas123** [hasadna/open-shot#294]
URL is from facebook

e.g this candidate
http://localshot.org.il/Nir.Barkat/
http://localshot.org.il/Ofer.Berkovich/

why is that so? I remember at one time I could add pictures properly the same way

**Comment by lotan1** [comment]
by upload or by link?
is it here: http://localshot.org.il/admin/avatar/avatar/ ?

**Comment by polinas123** [comment]
From users menu - add user - avatar url

**Comment by danielhers** [comment]
You are talking specifically about the candidate user page, right?
I'll add the avatar there.

**Comment by tbrisker** [comment]
fix does not fix.
