### ISSUE TITLE
changing candidate's name (not username) is not updated in the locality display

### ISSUE THREAD

**Issue by polinas123** [hasadna/open-shot#296]
example:

I manually created user Yael.Antebi without name or surname
it appears as Yael.Antebi on Jerusalem's locality page
now I modify the user to have Hebrew name and surname יעל ענתבי
It's saved but not updated on the locality page display.

might be related to this one?
https://github.com/hasadna/open-shot/issues/292

**Comment by lotan1** [comment]
http://localshot.org.il/Yael.Antebi/ ?

**Comment by polinas123** [comment]
Yes. Also on users list

**Comment by tbrisker** [comment]
#302

**Comment by tbrisker** [comment]
this is related to caching. it takes about 5 minutes for the locality page to be updated - right now it shows correctly on the locality page.
