### ISSUE TITLE
when candidate is female מועמד is not changed to מועמדת

### ISSUE THREAD

**Issue by polinas123** [hasadna/open-shot#297]
http://localshot.org.il/Yael.Antebi/

you can see here that gender is נקבה
http://localshot.org.il/admin/auth/user/286/

**Comment by tbrisker** [comment]
currently gender can only be specified by admin interface. opened #301 to allow users to update their gender.

**Comment by tbrisker** [comment]
#302

**Comment by lotan1** [comment]
dont wont to be not feminist but the default should be male otherwise all the candidate that we didnt specifie and statisticly about 80% of them will appear "אבי לוי מועמדת ברשימת נעל לראשות משהו"
