### ISSUE TITLE
Edit profile: יש להזין תוכן בשדה זה - מקום מגורים

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#307]
![pleaseinsertcontentinthisfield](https://f.cloud.github.com/assets/5072931/1216691/e380988a-2690-11e3-9d66-feb05638a2c3.PNG)
והשדה לא זמין לעריכה
תוצאה - שום מידע לא מתעדכן
אותה הודעה במשתמש שלי בגן יבנה וגם במעלה אבק
"אתנחתא קומית - תיבת "ספר לי על עצמך

**Comment by tbrisker** [comment]
#300
