### ISSUE TITLE
remove (תושבים למועמד) stats

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#312]
irrelevet isnt it?
10 מועמדים רשומים (19630 תושבים למועמד)
12 מועמדים רשומים (67033 תושבים למועמד)

**Comment by gl1000007** [comment]
אתה יכול ללמוד מזה על מידת ה"פעילות" של היישוב.
נניח שיש הרבה מועמדים על יישוב קטן, בטח קורה שם משהו מעניין. אולי היישוב מלא באקטיביסטים?
מצד שני, מעט מועמדים על יישוב גדול יכול אולי להגיד שטוב להם עם ראש הרשות הנוכחי, או שהתבצע שם איזה מהלך בלתי חוקי (השתקת מתחרים?), או תאוריית הקונספירציה החביבה עליך.
בכל אופן, למידע הזה יש משמעות והוא יוצר פתח לחקירה נוספת. אני רוצה לחשוב שגולשים חדי עין יבחינו בזה ויתחילו לחקור בעניין.

**Comment by tbrisker** [comment]
I agree with Lotan - this data is irrelevant to 95% of our users at least, not to mention that it might be misleading in localities where we didn't enter all the candidates. 
I would rather focus on more interesting stats - such as voting rates (see #329).
