### ISSUE TITLE
Retire Maale Avak

### ISSUE THREAD

**Issue by tbrisker** [hasadna/open-shot#315]
It seems like the editor event will be a good time to retire maale avak as the default page for unregistered users.
Any suggestions as to how we should choose the new default page? 
The one with most questions? most answers? most candidates? just a random one?
Note - do not remove maale avak from the DB as it will cause problems with search engines, just change the default page.

**Comment by lotan1** [comment]
must change
just spoke to or from mynet its his input as well

maybe by ip locality if its from active locality else random from the
active answerd localities

2013/9/30 tbrisker notifications@github.com

**Comment by tbrisker** [comment]
will change soon to localities with answers, but the welcome flatblock has to change

**Comment by lotan1** [comment]
http://localshot.org.il/admin/flatblocks/flatblock/6/

2013/10/6 tbrisker notifications@github.com

**Comment by tbrisker** [comment]
Retired. Right now should display random locality with answers.

**Comment by lotan1** [comment]
till we'll create homepage,
should be somthing that considers not only the first answer,
maybe above 10 questions

2013/10/6 tbrisker notifications@github.com
