### ISSUE TITLE
Allow candidate to post links to their profile

### ISSUE THREAD

**Issue by danielhers** [hasadna/open-shot#318]
The module django-links is already installed and the Candidate model supports the required fields, but the edit_profile form does not yet support adding links. Need to add the required controls to the form.

**Comment by danielhers** [comment]
What I discovered so far: the "links" app is very simple and doesn't do anything special.
The field is displayed in the admin interface for candidate objects because in polyorg/admin.py there is a LinksInline object which takes care of this.
We want to do something similar for user/views.py for edit_profile for candidates.

**Comment by danielhers** [comment]
I think the edit_profile form will just have hard-coded fields for Facebook profile, Youtube URL, etc., and these will be translated to Link objects, calling the add_link function in the view when the form is submitted. The admin form will still allow editing links as it does now (which is not so intuitive for users, but OK for admins).
@daonb , let's discuss how to do this, since you have experience with the links app. Although I messed around with it quite enough to understand some myself.

**Comment by tbrisker** [comment]
#302

**Comment by daonb** [comment]
what you're saying makes sense - Add the specialized fields to the form and in the view add the links.

**Comment by danielhers** [comment]
Yes, working on it.

**Comment by danielhers** [comment]
I'm actually pretty much done, as you can see on [my branch](https://github.com/danielhers/open-shot.git), but the only problem is that the icons are not found in the locations set by link_type.image. Is this set in the database?
