### ISSUE TITLE
Allow an author to edit his question

### ISSUE THREAD

**Issue by daonb** [hasadna/open-shot#32]
Maybe the author made a mistake?

**Comment by daonb** [comment]
Not sure he should... What happens if there are answers and we have a joker?

**Comment by david206** [comment]
+1,
At least let the author edit his question **before** there are any answers.

**Comment by tbrisker** [comment]
I;m on it.

**Comment by ozomer** [comment]
What about the candidates? They should be able to edit/delete their answers too.

... and somehow prevent them from deleting their promises the day after the elections.

**Comment by daonb** [comment]
Right, candidates should be able to edit their answers, but that's another ticket
