### ISSUE TITLE
Richer formatting for candidate list platform (מצע)

### ISSUE THREAD

**Issue by danielhers** [hasadna/open-shot#325]
Currently the platform is shown as plain text with no support for links or images, and even newlines are omitted.
Some lists publish their platform as an image, so we either have to copy the text manually or using OCR, or to post a link to the image.
What's more important is to respect newlines in the platform text, to make it readable.
Example:
![selection_039](https://f.cloud.github.com/assets/263363/1251443/b099bfcc-2b28-11e3-9bb4-c1b36e61546d.png)
becomes:
![selection_038](https://f.cloud.github.com/assets/263363/1251436/9c409b54-2b28-11e3-807d-58e74c20e9a7.png)

**Comment by tbrisker** [comment]
duplicate #56
