### ISSUE TITLE
Add previous elections voting rates to locality page

### ISSUE THREAD

**Issue by tbrisker** [hasadna/open-shot#329]
if we can find them...

**Comment by lotan1** [comment]
מה שאני מכיר זה באקסלים נפרדים לפי רשות
http://rashoyot.moin.gov.il/default.aspx?m=m

2013/10/2 tbrisker notifications@github.com

**Comment by lotan1** [comment]
Here it is
http://www.moin.gov.il/Subjects/Bchirot/Documents/achoz.xls

2013/10/2 lotan rosenblum lotanro@gmail.com

> מה שאני מכיר זה באקסלים נפרדים לפי רשות
> http://rashoyot.moin.gov.il/default.aspx?m=m

2013/10/2 tbrisker notifications@github.com

**Comment by lotan1** [comment]
done https://docs.google.com/spreadsheet/ccc?key=0AibPNoUcfXcMdEctN0VRT041c3dlYm5ZcFptcW9PR3c&usp=drive_web#gid=0
