### ISSUE TITLE
עורכים מקבלים 500 כשמנסים למחוק מועמד מרשימה ברשות שלהם

### ISSUE THREAD

**Issue by polinas123** [hasadna/open-shot#332]
זה קורה אחרי שנוצרו (מסיבה לא ברורה לי) כפילויות ברשימות. מועמד מסויים מופיע פעמיים וכשמנסים למחוק אחד מהם לא מצליחים.
בממשק ניהול אני רואה שיש באמת שני יוזרים (זה לא קשור לדחיפה המרוכזת של מועמדים)

אין לי דוגמא טובה, מחקתי כבר את מה שהיה כפול וידעתי שכפול.

**Comment by tbrisker** [comment]
should be fixed on next version. need to discover also how duplicates are created.

**Comment by tbrisker** [comment]
should be fixed now. reopen if still exists.
