### ISSUE TITLE
candidates are not displayed in dropdown menu for adding candidates to lists

### ISSUE THREAD

**Issue by polinas123** [hasadna/open-shot#333]
if user is set to "is candidate" editor will not see it on the menu
the workaround is press יצירה with no item selected and then all users are visible

**Comment by tbrisker** [comment]
the first part is a feature, not bug - users should not be set to is_candidate manually, adding them to a list automatically marks them as is_candidate.
the second part is a serious bug - only local users who are not editors or candidates should be available to add as candidates (I am guessing this is how we got the duplicate candidates in #332 )
