### ISSUE TITLE
bug preventing changing avatar when logged in via faceboook

### ISSUE THREAD

**Issue by tbrisker** [hasadna/open-shot#338]
from facebook:
Amos Shtibelman 
יש לכם בעייה בתהליך ההרשמה. ניסיתי להכנס עם פרופיל הפייסבוק שלי תוך שאני מנסה להחליף תמונת פרופיל שתשמש אותי. קיבלתי הודעת שגיאה שעצרה אותי בתהליך ההרשמה, ניסיתי לעשות זאת עם מספר תמונות וקיבלתי את אותה התוצאה.

https://www.facebook.com/photo.php?fbid=744287248921481&set=a.210740292276182.66759.167171689966376&type=1&comment_id=116473366&offset=0&total_comments=3

**Comment by tbrisker** [comment]
דיווח מפורט:
שאני מנסה לעשות לוג אין עם חשבון הפייסבוק הודעת השגיאה היא : 413 entity to long.
 כמו כן לא ניתן בכלל לעשות לוג אין עם חשבון הגוגל שלי הוא אפילו לא מביא אותי לאפשרות של שם וסיסמה.
לידיעתך אני עובד עם ipad אם יש לכך משמעות.

**Comment by daonb** [comment]
#416
