### ISSUE TITLE
לא ניתן להפעיל יוזר שנוצר עם שמשתמש בעברית

### ISSUE THREAD

**Issue by polinas123** [hasadna/open-shot#339]
או שצריך לתקן או שצריך לרשום בבירור שיש עם זה בעיה
לדוגמא
http://localshot.org.il/admin/auth/user/710/

תנסו להפוך לפעיל ומקבלים הודעה ששם המשתמש לא חוקי
זה דף של מועמדת שניסתה להירשם בעצמה וזה מה שיצא
אז חשוב לטפל בזה

**Comment by tbrisker** [comment]
duplicate #149
