### ISSUE TITLE
please delete example.com from sites

### ISSUE THREAD

**Issue by polinas123** [hasadna/open-shot#340]

**Comment by tbrisker** [comment]
Currently all questions and users are linked to site example.com for some reason - DO NOT DELETE FROM DB!

**Comment by polinas123** [comment]
This is why I didn't delete it. can it be fixed?

**Comment by lotan1** [comment]
Leads to Server Error (500) when adding profile to user from admin panel,
either for localshot.org.il and example.co.il

2013/10/5 polinas123 notifications@github.com

> This is why I didn't delete it. can it be fixed?

**Comment by tbrisker** [comment]
@lotan1 - your comment doesn't seem to be related as it doesn't matter which site it is. please open new issue with steps to reproduce

**Comment by tbrisker** [comment]
fixing this should include moving all objects from example.com to localshot.org.il and making sure no new objects are created there before finally removing unused sites from DB - @daonb ?

**Comment by daonb** [comment]
wouldn't renaming "example.com" to "localshot
org.il" do the trick?

**Comment by tbrisker** [comment]
deleted localshot.org.il and test.com and renamed example.com to localshot.org.il.
9 profiles may have been affected as they were related to localshot and not example - please check manually @polinas123 (some may not be active at all):
laura.vherton
ofek.birnholtz
ofekbirnholtz
edna.friedman
debi.benami
yafa.sehalo
meir.margalit
rona.orovano
roy.folkman

**Comment by polinas123** [comment]
yes, all mine. all active.
I'll check them thanks

2013/10/6 tbrisker notifications@github.com

> deleted localshot.org.il and test.com and renamed example.com to
> localshot.org.il.
> 9 profiles may have been affected as they were related to localshot and
> not example - please check manually @polinas123https://github.com/polinas123(some may not be active at all):
> laura.vherton
> ofek.birnholtz
> ofekbirnholtz
> edna.friedman
> debi.benami
> yafa.sehalo
> meir.margalit
> rona.orovano
> roy.folkman
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/340#issuecomment-25765466
> .

## 

localshot.org.il _השו"ת המקומי_
_אתר שאלות ותשובות לבחירות המקומיות_
בואו. שאלו. השפיעו

**Comment by polinas123** [comment]
@tbrisker, עכשיו כשאני נכנסת לכל אחד מהם לא מופיע להם פרופיל אבל הם פעילים
(אני מניחה שזה בגלל השינוי הנ"ל)
אם אני מנסה להוסיף פרופיל ("הוספת פרופיל") אני מקבלת 500
איך אפשר לקשר להם פרופיל בלי למחוק אותם? אלה מועמדים שכבר שלחנו להם שם
משתמש וססמא והם מקושרים לרשימות ולכן ואני מעדיפה מאוד להימנע מיצירת שם חדש.

2013/10/6 tbrisker notifications@github.com

> deleted localshot.org.il and test.com and renamed example.com to
> localshot.org.il.
> 9 profiles may have been affected as they were related to localshot and
> not example - please check manually @polinas123https://github.com/polinas123(some may not be active at all):
> laura.vherton
> ofek.birnholtz
> ofekbirnholtz
> edna.friedman
> debi.benami
> yafa.sehalo
> meir.margalit
> rona.orovano
> roy.folkman
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/340#issuecomment-25765466
> .

## 

localshot.org.il _השו"ת המקומי_
_אתר שאלות ותשובות לבחירות המקומיות_
בואו. שאלו. השפיעו

**Comment by daonb** [comment]
יעזור לקבל את הכתובת שנותנת 500...

2013/10/6 polinas123 notifications@github.com

> @tbrisker, עכשיו כשאני נכנסת לכל אחד מהם לא מופיע להם פרופיל אבל הם פעילים
> (אני מניחה שזה בגלל השינוי הנ"ל)
> אם אני מנסה להוסיף פרופיל ("הוספת פרופיל") אני מקבלת 500
> איך אפשר לקשר להם פרופיל בלי למחוק אותם? אלה מועמדים שכבר שלחנו להם שם
> משתמש וססמא והם מקושרים לרשימות ולכן ואני מעדיפה מאוד להימנע מיצירת שם
> חדש.
> 
> 2013/10/6 tbrisker notifications@github.com
> 
> > deleted localshot.org.il and test.com and renamed example.com to
> > localshot.org.il.
> > 9 profiles may have been affected as they were related to localshot and
> > not example - please check manually @polinas123<
> > https://github.com/polinas123>(some may not be active at all):
> > laura.vherton
> > ofek.birnholtz
> > ofekbirnholtz
> > edna.friedman
> > debi.benami
> > yafa.sehalo
> > meir.margalit
> > rona.orovano
> > roy.folkman
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/hasadna/open-shot/issues/340#issuecomment-25765466>
> > .
> 
> ## 
> 
> localshot.org.il _השו"ת המקומי_
> _אתר שאלות ותשובות לבחירות המקומיות_
> בואו. שאלו. השפיעו
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/340#issuecomment-25765806
> .

## 

http://yeda.us/daonb

**Comment by polinas123** [comment]
בני, בעיקרון כבר סידרנו את זה תומר ואני, אז לא יודעת כמה רלוונטי כרגע,
הכתובות היו העמודים של כל אחד מהרשומים מעלה בממשק הניהול. אם זה להבא, ארשום
(אני משתדלת לרוב לתת דוגמא).

בתאריך 7 באוקטובר 2013 08:40, מאת benny daon notifications@github.com:

> יעזור לקבל את הכתובת שנותנת 500...
> 
> 2013/10/6 polinas123 notifications@github.com
> 
> > @tbrisker, עכשיו כשאני נכנסת לכל אחד מהם לא מופיע להם פרופיל אבל הם
> > פעילים
> > (אני מניחה שזה בגלל השינוי הנ"ל)
> > אם אני מנסה להוסיף פרופיל ("הוספת פרופיל") אני מקבלת 500
> > איך אפשר לקשר להם פרופיל בלי למחוק אותם? אלה מועמדים שכבר שלחנו להם שם
> > משתמש וססמא והם מקושרים לרשימות ולכן ואני מעדיפה מאוד להימנע מיצירת שם
> > חדש.
> > 
> > 2013/10/6 tbrisker notifications@github.com
> > 
> > > deleted localshot.org.il and test.com and renamed example.com to
> > > localshot.org.il.
> > > 9 profiles may have been affected as they were related to localshot
> > > and
> > > not example - please check manually @polinas123<
> > > https://github.com/polinas123>(some may not be active at all):
> > > laura.vherton
> > > ofek.birnholtz
> > > ofekbirnholtz
> > > edna.friedman
> > > debi.benami
> > > yafa.sehalo
> > > meir.margalit
> > > rona.orovano
> > > roy.folkman
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/hasadna/open-shot/issues/340#issuecomment-25765466>
> > > .
> > 
> > ## 
> > 
> > localshot.org.il _השו"ת המקומי_
> > _אתר שאלות ותשובות לבחירות המקומיות_
> > בואו. שאלו. השפיעו
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/hasadna/open-shot/issues/340#issuecomment-25765806>
> > .
> 
> ## 
> 
> http://yeda.us/daonb
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/340#issuecomment-25786013
> .

## 

localshot.org.il _השו"ת המקומי_
_אתר שאלות ותשובות לבחירות המקומיות_
בואו. שאלו. השפיעו
