### ISSUE TITLE
Editor notification links to example.com

### ISSUE THREAD

**Issue by danielhers** [hasadna/open-shot#344]
I got the "new candidate" email because I'm a local editor, and the link to the candidate page was into example.com rather than localshot.org.il.
This email is generated from user/templates/user/emails/editors_new_candidate.html which uses ROOT_URL, which is set to be the URL of the site whose ID is 1. Why is this example.com?

**Comment by tbrisker** [comment]
related to #340

**Comment by tbrisker** [comment]
fixed
