### ISSUE TITLE
promote our site on google

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#350]
maybe need to add meta description 
@talbatz
https://docs.google.com/spreadsheet/ccc?key=0AibPNoUcfXcMdDgyeEZnb3RVd3k0RVBFYkFSV2N5b0E&usp=drive_web#gid=0

**Comment by M4XIMU5** [comment]
הצעה ל Meta Description
לוקאלשוט (השו"ת המקומי) הוא אתר שהוקם במיוחד לקראת הבחירות לעיריות ברשויות המקומיות, מאפשר לאזרחים לשאול את המועמדים שאלות מוניציפליות ולקבל מכל המועמדים לבחירות' תשובות בשביל לבצע את הבחירה המושכלת ביותר לקראת הבחירות המקומיות הקרובות ב 22.10.13.

**Comment by M4XIMU5** [comment]
הצלחתי לשלב כאן 7 מילות חיפוש מתוך הטבלה. אם זה מספיק טוב אז נשאר רק להטמיע את זה.

**Comment by lotan1** [comment]
for "השו"ת המקומי":
השו"ת המקומי: רשימת שאלות (ירושלים)
localshot.org.il/‎Translate this page
מצביע בבחירות המקומיות? ברוכים הבאים לאתר השו"ת (שאלות ותשובות) המקומי. בעזרת האתר יכולים תושבים להעלות שאלות למועמדים השונים ולהשוות בין התשובות שלהם.

חיפושים כמו
"שאלות ותשובות לקראת הבחירות המוניציפליות" 
לא נמניב אותנו

אבל מכוסה באדוורדס
meanwhile 115,000 Impressions at google adwords
