### ISSUE TITLE
דגל אדום יושב קרוב מדי לתמיכה בשאלה - אנשים מתבלבלים

### ISSUE THREAD

**Issue by polinas123** [hasadna/open-shot#352]
קיבלתי שני דגלים בארבע שעות
די :)

**Comment by tbrisker** [comment]
add a confirm dialog before flagging

**Comment by lotan1** [comment]
דיגול רק בתוך עמודי השאלות
תמיכה בעמוד הראשי

2013/10/7 tbrisker notifications@github.com

**Comment by gl1000007** [comment]
להפריד את הכפתורים ויזואלית, שיהיה קצת רווח ביניהם, וגם שייראו כמו כפתורים נפרדים עם 4 פינות מעוגלות לכל כפתור.
אפשר להתחיל מ- 10px ואם צריך אז להגדיל את הרווח, לפי משוב מפולינה.

**Comment by lotan1** [comment]
בהמשך לאלכס בגוגל גרופ
must change
כרגע בעמוד רשות יש רק דגלים אדומים,
צריך רק כפתורי תמיכה או ביטול תמיכה (ללא רשומים יפנה להרשמה)
ובתוך עמוד השאלה, תמיכה לצד דיגול (או מחיקה לבעלים ולעורכים)
#351 #357

**Comment by danielhers** [comment]
There are too many suggestions here for how to resolve this. What's the decision? To remove the "flag question" button from the question list and only show it in the question details page?

**Comment by Talbatz** [comment]
maybe a better looking set of icons / buttons can solve the issue? i can send an alternative option if you guys are intrerested

**Comment by lotan1** [comment]
diffrent issues:
-remove flags from locality page
-add support q to locality page for every user (redirect to login)
-add support q to q page for every user (redirect to login)
-improve icons

2013/10/8 Talbatz notifications@github.com

**Comment by danielhers** [comment]
Do you think there should be an [icon](http://fortawesome.github.io/Font-Awesome/icons/) for "add answer"?
Maybe http://fortawesome.github.io/Font-Awesome/icon/reply/

**Comment by Talbatz** [comment]
that specific icon you linked to may be a lil' more suitable for a 'back' button... i think we should go for something more obvious/literal like a question mark with a little + next to it. 

Generally, i recommend keeping a consistent look and feel  to all the button/icons/action on the site, it would make the site more coherent.

**Comment by danielhers** [comment]
Anything else?

(Right now the answer button is text - "Answer the Question" / "Change Your Answer". If a clear enough icon with enough visual presence is suggested, I'll change it.)

**Comment by tbrisker** [comment]
closing this now. if you have any more related issues - open new issues as this issue has become overloaded with ideas for various changes.
