### ISSUE TITLE
Design a large Note image for List Page

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#358]
![zedek](https://f.cloud.github.com/assets/5072931/1283088/4a92a1e8-2f7f-11e3-9866-fc0763179412.PNG)
The image size is exactly like candidate the and user avatar: 140x140 px.
The note should be empty and letters will be added later by code.
This is bullet no.1 in the [List page in the spec](https://docs.google.com/document/d/1cEObTn5NWn-BjkWpSiqpsmy8zCMGVmmt4h9rv8XaRnE/edit#bookmark=id.nzrbtpczb2s4)
@M4XIMU5 this is yours. When you finish please post a link here and I'll open a separate issue for applying the picture in code.

**Comment by lotan1** [comment]
If its going to be big, why not do it as the official one that going to be on Kalpi?

**Comment by gl1000007** [comment]
design issue, leave it for the next elections.
