### ISSUE TITLE
Design Default avatar, Unregistered User Avatar

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#359]
Current default avatar is Gravatar's default image.

The Default Avatar is a person's silhouette: one for male and one for female. As far as I know, choosing a gender while registering a must.

The Unregistered user is intended for use on the List Page, for candidates that are in the list but not yet created a user on the site:
![shabzak](https://f.cloud.github.com/assets/5072931/1283274/5f5860ce-2f82-11e3-8226-5e8c88d3e883.PNG)
Since we don't know what is the gender of unregistered users, we'll use the default avatar for male + a big question mark in the middle. There should be a difference in color from the default avatars. Say, blue and red.

Below is a very artistic sketch made with the superior software of Paint:
![3people](https://f.cloud.github.com/assets/5072931/1283431/7292427a-2f84-11e3-9764-1e18a7ffc582.png)

Note: Size is a variable, See #310.

This is a design task only. When finished, I'll open new separate issues for applying the graphics in code.

@M4XIMU5

**Comment by tbrisker** [comment]
handled by #413, replaced the default avatar.

**Comment by gl1000007** [comment]
+1
