### ISSUE TITLE
להוסיף לינק להרשמה עבוד מועמדים במסך ההרשמה

### ISSUE THREAD

**Issue by polinas123** [hasadna/open-shot#368]
מועמדים צריכים להיות מזוהים על ידינו ולהיות משויכים לרשימה.
לכן מועמד שאין לו שם משתמש וססמא ואין לו עורך לפנות אליו לא ידע מה לעשות מרגע שנרשם דרך האופציות האפשריות
בנוסף, אחרי שניצור משתמשים לרוב המועמדים מהאקסל של משרד הפנים - הם יצטרכו לקבל מאיתנו פרטי הרשמה ממילא.

בקיצור - להפנות אותם לגוגלדוק ממסך ההרשמה ולא רק ממסך האודות שאליו מעטים יגיעו

**Comment by lotan1** [comment]
אולי להדביק בנתיים את שני הקישורים כמו הכפתורים באודות לטופס מועמדים ולטופס
עורכים

בתאריך 8 באוקטובר 2013 18:11, מאת polinas123 notifications@github.com:

**Comment by danielhers** [comment]
לאן בדיוק צריך להפנות?

**Comment by polinas123** [comment]
לטופס שהכפתור בעמוד האודות מפנה אליו

וכמו שלוטן הציע, אפשק להוסיף גם "רישום עורכים"

2013/10/9 Daniel Hershcovich notifications@github.com

> לאן בדיוק צריך להפנות?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/368#issuecomment-25961440
> .

## 

localshot.org.il _השו"ת המקומי_
_אתר שאלות ותשובות לבחירות המקומיות_
בואו. שאלו. השפיעו

**Comment by lotan1** [comment]
זה רק רעיון זמני
להדביק צורה כלשהי של הכפתורים שיש באודות ומפנים לעמודי הטפסים להרשמת עורכים
והרשמת מועמדים

2013/10/9 Daniel Hershcovich notifications@github.com
