### ISSUE TITLE
candidate image not displayed on candidate list page

### ISSUE THREAD

**Issue by polinas123** [hasadna/open-shot#369]
IMAGE URL
https://fbcdn-sphotos-b-a.akamaihd.net/hphotos-ak-prn1/601753_521097534644041_708687844_n.jpg

USER 293
http://localshot.org.il/Hanoch.Verdiger/

**Comment by polinas123** [comment]
עוד דוגמא
http://localshot.org.il/Shmuel.Shkedi/

**Comment by polinas123** [comment]
http://localshot.org.il/tamir.n/

**Comment by tbrisker** [comment]
should work now, might need to delete the url, save the user, and then add the url again for it to work.
