### ISSUE TITLE
Count, show and order by number of answers for lists

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#386]
count combined no of answers for candidate lists
Im not shure about viewing it
and order the lists notes by no of answers (consider precentage)

**Comment by gl1000007** [comment]
can be applied, but:
1. is it really necessary, considering our time constraints?
2. keep the option to sort alphabetically along with the sorting by number of answers.

IMO, we don't have time for it, maybe after elections.

**Comment by daonb** [comment]
I think it's important to promote the candidate lists that do answer questions.

**Comment by lotan1** [comment]
+1 ?

**Comment by daonb** [comment]
@lotan1 what is "+1 ?"? you can do "+ 0.5" if you're not sure, but your reply makes no sense to me

**Comment by lotan1** [comment]
Sorry, but its funny, Im just getting use to it.
Im voting for it anyway.
בתאריך 17 באוק 2013 08:28, "benny daon" notifications@github.com כתב:

**Comment by daonb** [comment]
depending on how funny it gets, you can comment with :-), lol
(laugh-out-loud) or ROFL (rolling on the floor laughing)

On 17 October 2013 09:47, lotan1 notifications@github.com wrote:

> Sorry, but its funny, Im just getting use to it.
> Im voting for it anyway.
> בתאריך 17 באוק 2013 08:28, "benny daon" notifications@github.com כתב:
> 
> > @lotan1 https://github.com/lotan1 what is "+1 ?"? you can do "+ 0.5"
> > if
> > you're not sure, but your reply makes no sense to me
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/hasadna/open-shot/issues/386#issuecomment-26481864>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/386#issuecomment-26482480
> .

## 

http://yeda.us/daonb

**Comment by gl1000007** [comment]
I see a commit here. Close?

**Comment by danielhers** [comment]
The "show" part isn't implemented yet.
