### ISSUE TITLE
Add an outline to candidate list and list list in Locality page

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#387]
![tadrich](https://f.cloud.github.com/assets/5072931/1304736/0d191526-3188-11e3-961c-0d48027aa2f4.png)
Further to the discussion [תדריך מסודר](https://groups.google.com/d/msg/localshot/JZFIRNsmdy8/JeMK3fge92MJ) in the Group.
Line style is identical to existing lines, for example in the question list, including the rounded edges.

The outline gives the user a hint that there is more content under the fold, causing them to scroll.
Similar to the mobile apps of Instagram, Facebook, and many more.

**Comment by daonb** [comment]
IMO, we need more than a hint. have you tried pushing the candidates to the side and bringing the questions to the top? questions are our unique, dynamic content and we should give them a prominent place and above the fold.

**Comment by gl1000007** [comment]
Have a glimpse at any mobile app which displays a list of objects (FB?) and look at the bottom of the screen. In most cases, the lowest object is cut off by the fold. In that case, you can conclude that the object continues under the fold, and then you scroll down.
So, that line is all the hint we need. _Maybe_ it can be a little thicker, but nothing beyond that point.

BTW there is a long-term solution in the [spec (marks 8-11)](https://docs.google.com/file/d/0B3yaQaorsX55U1RNQVVDWlYxR28/edit?usp=sharing).

**Comment by daonb** [comment]
I don't know of any app that use its first page to display static
information, keeping dynamic content hidden. As a returning user there's
nothing to interest me in the home page of my locality.

**Comment by tbrisker** [comment]
How about making all the candidate listings hidden by default and only displaying it when clicking on a button next to locality name, maybe with an nice slide toggle effect?
