### ISSUE TITLE
Design new small note images

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#388]
Replacing ![note yellow](https://f.cloud.github.com/assets/5072931/1309173/9b9a4cb4-31da-11e3-903e-57de8f979f50.png) and ![note white](https://f.cloud.github.com/assets/5072931/1309177/a2ae6d46-31da-11e3-85b8-b1a3885e638e.png) from the [assets](https://drive.google.com/folderview?id=0B3yaQaorsX55X2dzdFJWbFhLY3M&usp=sharing) library.
For use in #209 and #310.
Later I'll put links to more specific issues.
@M4XIMU5

**Comment by lotan1** [comment]
what about that?
can it be meanwhile biger, rectangle, bold letters?

**Comment by gl1000007** [comment]
design issue, leave it for the next elections.
