### ISSUE TITLE
Resize the candidate Avatar to 140x140px with 10px horizontal spacing

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#390]
Essentially resize only the avatar and leave the text as it is.
#389

**Comment by tbrisker** [comment]
140 is too large - only two candidates will be shown per row. change to to 100. (currently it is 75)

**Comment by gl1000007** [comment]
Look at the column sizes in the spec. There is a place for 4 candidates in a row.
Look at [the numbers on the top, and marks 6-10](https://docs.google.com/document/d/1cEObTn5NWn-BjkWpSiqpsmy8zCMGVmmt4h9rv8XaRnE/edit?usp=docslist_api).
Also, there is a link to the specific part in the spec, at the META ISSUE page.

**Comment by gl1000007** [comment]
can be closed?
