### ISSUE TITLE
לבקש מכל זכות להוסיף אותנו בחלק העליון של עמוד הבחירות המקומיות

### ISSUE THREAD

**Issue by tbrisker** [hasadna/open-shot#410]
http://www.kolzchut.org.il/he/%D7%91%D7%97%D7%99%D7%A8%D7%95%D7%AA_%D7%9C%D7%A8%D7%A9%D7%95%D7%99%D7%95%D7%AA_%D7%94%D7%9E%D7%A7%D7%95%D7%9E%D7%99%D7%95%D7%AA

**Comment by lotan1** [comment]
אני על זה
אקשר גם אליהם מהאודות שלנו עם הפנייה לשאלות בנושאי בחירות ונהליהן

2013/10/12 tbrisker notifications@github.com
