### ISSUE TITLE
In public profile: questions I'm following, do not display buttons

### ISSUE THREAD

**Issue by danielhers** [hasadna/open-shot#412]
Need to pass parameters to _question.html so that the question preview is as clean as possible in this view.

**Comment by daonb** [comment]
There's no way to pass a parameter. probably simpler to create a new file _question_by_owner.html and include the original _question.html

**Comment by danielhers** [comment]
Why not? Just do
{% with can_vote=False %}
  {% include "qa/_question.html" %}
{% endwith %}

And read can_vote inside _question.html (in addition to the template tags
question|can_vote:user, question|can_upvote:user and
question|can_downvote:user.

**Comment by daonb** [comment]
+1.
You live and learn.

On 13 October 2013 15:50, Daniel Hershcovich notifications@github.comwrote:

> Why not? Just do
> {% with can_vote=False %}
> {% include "qa/_question.html" %}
> {% endwith %}
> 
> And read can_vote inside _question.html (in addition to the template tags
> question|can_vote:user, question|can_upvote:user and
> question|can_downvote:user.
> 
> On 13 October 2013 16:44, benny daon notifications@github.com wrote:
> 
> > There's no way to pass a parameter. probably simpler to create a new
> > file
> > _question_by_owner.html and include the original _question.html
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/hasadna/open-shot/issues/412#issuecomment-26218042>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/412#issuecomment-26218159
> .

## 

http://yeda.us/daonb

**Comment by daonb** [comment]
only the paramter should be

On 13 October 2013 16:06, benny daon bennydaon@gmail.com wrote:

> +1.
> You live and learn.
> 
> On 13 October 2013 15:50, Daniel Hershcovich notifications@github.comwrote:
> 
> > Why not? Just do
> > {% with can_vote=False %}
> > {% include "qa/_question.html" %}
> > {% endwith %}
> > 
> > And read can_vote inside _question.html (in addition to the template tags
> > question|can_vote:user, question|can_upvote:user and
> > question|can_downvote:user.
> > 
> > On 13 October 2013 16:44, benny daon notifications@github.com wrote:
> > 
> > > There's no way to pass a parameter. probably simpler to create a new
> > > file
> > > _question_by_owner.html and include the original _question.html
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/hasadna/open-shot/issues/412#issuecomment-26218042>
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/412#issuecomment-26218159
> > .
> 
> ## 
> 
> http://yeda.us/daonb

## 

http://yeda.us/daonb
