### ISSUE TITLE
change default avatar to something more elegant

### ISSUE THREAD

**Issue by polinas123** [hasadna/open-shot#413]

**Comment by Talbatz** [comment]
Something like that?

http://www.newportoak.com/wp-content/uploads/default-avatar.jpg

**Comment by daonb** [comment]
![default-avatar 1](https://f.cloud.github.com/assets/36852/1320012/df288ee4-3330-11e3-9311-7198b3b88948.png)

**Comment by gl1000007** [comment]
Looks nice. +1

**Comment by lotan1** [comment]
much better!
but seems now that candidate without avatar wont show his name under his avatar when answering
http://localshot.org.il/277/qna/
