### ISSUE TITLE
"413 entity too large" when adding picture to candidate profile

### ISSUE THREAD

**Issue by polinas123** [hasadna/open-shot#416]
adding the avatar as candidate on an existing profile

attached error screenshot and picture
![shay_engler_pic](https://f.cloud.github.com/assets/5359949/1320371/9ac2384c-3356-11e3-9658-a12781fa5cd3.jpg)
![5774 02 08 17 50 20](https://f.cloud.github.com/assets/5359949/1320372/a13a52ea-3356-11e3-89ac-75b003837d57.png)

**Comment by tbrisker** [comment]
related to #338 ?

**Comment by polinas123** [comment]
no idea. this was login with username and password

**Comment by lotan1** [comment]
קורה לי כשמנסה להעלות תמונות גדולות מדי
עברתי ללקישורי תמונות פרופיל בפייסבוק מהניהול
אולי אפשר לאפשר למשתמשים לקשר תמונה ולא רק להעלות כמו שניתן היה בעבר?

2013/10/13 polinas123 notifications@github.com

**Comment by daonb** [comment]
It's an nginx limit. I've changed the limit to 5MB. please try uploading again and close the issue if all is well

**Comment by tbrisker** [comment]
should be fixed.
