### ISSUE TITLE
Remove the view of no` of listed candidates at locality page

### ISSUE THREAD

**Issue by lotan1** [hasadna/open-shot#417]
its a lot anyway and dosnt say anything

**Comment by daonb** [comment]
I think we should count only the 'verified' candidates - those candidates that have real people connected to them. @tbrisker, I saw you're import command added the candidates as verified, It could be better to add them as unverified and change it only when the editor uses the special form. This way we can count the number of candidates registered.

**Comment by tbrisker** [comment]
remove. the number doesn't say anything right now, and showing we only have 2-4 active candidates isn't a good idea either.

**Comment by gl1000007** [comment]
+1 to @daonb. And,
The number has a meaning - it can tell about the "activeness" of a locality in a vert fast way, before you even notice the candidate and party list.
