### ISSUE TITLE
looks like sorting the candidates in list by position isn't displayed

### ISSUE THREAD

**Issue by polinas123** [hasadna/open-shot#422]
http://localshot.org.il/42/qna/?list=86

בדוגמא הזו ארנון אברמוב מוגדר כ 1 ולא מופיע כ 1
לא לכל המועמדים יש מספר מוגדר אבל מי שיש לו, בעיקר הראשונים, לא מופיע לפי הסדר של הרשימה

**Comment by tbrisker** [comment]
candidates without ordinal appear before candidate with ordinal.

**Comment by polinas123** [comment]
אוי. זה קקי.
אפשר לעשות הפוך?

2013/10/14 tbrisker notifications@github.com

> candidates without ordinal appear before candidate with ordinal.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/422#issuecomment-26265577
> .

## 

localshot.org.il _השו"ת המקומי_
_אתר שאלות ותשובות לבחירות המקומיות_
בואו. שאלו. השפיעו

**Comment by tbrisker** [comment]
after checking again seems like there is a problem with ordering even if all candidates do have an ordinal, for example here: http://localshot.org.il/po/list/46

**Comment by danielhers** [comment]
According to [polyorg/models.py line 85](https://github.com/hasadna/open-shot/blob/dev/polyorg/models.py#L85), it looks like they're sorted in reverse order of ordinal. Shouldn't it be ascending order?
Also, it doesn't seem to agree with the order you showed in the אמת list in תל אביב יפו, where the apparent order is 3,2,1,4.

**Comment by lotan1** [comment]
#386
