### ISSUE TITLE
Have you already voted? version 2

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#440]
A simpler version of #208.
![votedv2](https://f.cloud.github.com/assets/5072931/1368919/16d8fc0e-39c9-11e3-8153-ea9a04a185ff.png)

This version doesn't require potntially complicated percent calaulation, only a simple counter.
Other issues have been updated to link here.
Please asign to "election day" milestone.

[text deleted, moved to a separate issue, listed in a comment below]

**Comment by michalten** [comment]
I guess this should be closed...

**Comment by gl1000007** [comment]
נשאיר לבחירות הבאות...
