### ISSUE TITLE
Bill detail redesign

### ISSUE THREAD

**Issue by daonb** [hasadna/open-shot#456]
![keneset-law-page](https://cloud.githubusercontent.com/assets/36852/2939369/5a696290-d944-11e3-8ffc-d6a4fce75b9f.jpg)

**Comment by gl1000007** [comment]
First impression: Nice!
Why a redesign was needed?

**Comment by gl1000007** [comment]
Ummm... are you sure this is the right repo your'e posting to?

**Comment by daonb** [comment]
You're right, it's the wrong repo...

https://github.com/hasadna/Open-Knesset/issues/227
