### ISSUE TITLE
Add an about page

### ISSUE THREAD

**Issue by daonb** [hasadna/open-shot#47]
so people know what it's all about

**Comment by maayan** [comment]
See suggested text here: https://docs.google.com/document/d/1uShqtHF21cdkc0AoAM1_5oTFdqH3wjIcd4Qx_34uvRc/edit
(who should I share it with?)

**Comment by daonb** [comment]
first version is on the live demo, but it still needs html-ing. @maayan please point your browser at http://okqa.herokuapp.com/admin/flatpages/flatpage/1/ and add a bit of formatting

**Comment by maayan** [comment]
Did some paragraphing. Do we have a contact form (to contact team)? I'll link to it from the "About" page

**Comment by daonb** [comment]
we have an address: qa@hasadna.org.il
