### ISSUE TITLE
תמיכה בפורמט מעוצב לשאלות ותשובות

### ISSUE THREAD

**Issue by daonb** [hasadna/open-shot#56]
בעיקר בקישורים, אבל גם בהבלטות. לדוגמא:
http://havoda.yeda.us/q/%D7%94%D7%90%D7%9D-%D7%90%D7%AA%D7%9D-%D7%99%D7%95%D7%93%D7%A2%D7%99%D7%9D-%D7%9E%D7%94-%D7%94%D7%99%D7%90-%D7%9B%D7%9C%D7%9B%D7%9C%D7%AA-%D7%97%D7%95%D7%91/

**Comment by lotan1** [comment]
תמיכה בפורמט מעוצב גם לפרופיל המועמד!

**Comment by tbrisker** [comment]
possible direction: https://github.com/aljosa/django-tinymce
