### ISSUE TITLE
Make Facebook sharing more informative

### ISSUE THREAD

**Issue by daonb** [hasadna/open-shot#62]
Need to add meta keyowrds on the pages so that facebook will use the right title when ppl share a page from the site.

**Comment by daonb** [comment]
here's a bit old explanation I found about facebook publisher: http://webapps.stackexchange.com/questions/6745/how-does-facebook-publisher-select-the-image-title-and-content-from-a-shared

**Comment by lotan1** [comment]
חשוב! בהצלחה עם זה

**Comment by daonb** [comment]
I believe it's solved. What's missing?
![image](https://f.cloud.github.com/assets/36852/1002694/90cb22e4-0a80-11e3-93f7-6dff0a3e2ae4.png)

**Comment by lotan1** [comment]
pictures?

**Comment by daonb** [comment]
that's another issue.  I'm on it, but you should close this one and open a
new one.

On 24 August 2013 21:15, lotan1 notifications@github.com wrote:

> pictures?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/62#issuecomment-23213659
> .

## 

http://yeda.us/daonb
