### ISSUE TITLE
Add a counter for remaining # of chars left 

### ISSUE THREAD

**Issue by idoivri** [hasadna/open-shot#67]
In order for the user to see how far she is from the max number of 500 chars,
a counter (such as Twitter's character counter) is needed somewhere above or below a question/answer textbox.

Cheers!

**Comment by daonb** [comment]
Now, we need to do the same for the answers

**Comment by amirnissim** [comment]
Done
https://github.com/amirnissim/okqa/commit/f76ff129589a9babcef97c4e2e4c14be18ab83e4
