### ISSUE TITLE
Add a section for Users

### ISSUE THREAD

**Issue by daonb** [hasadna/open-shot#75]
Showing the most active users, etc and the user detail pages.

**Comment by lotan1** [comment]
ארצית?
בכל מקרה לא מעניין לדעתי

**Comment by gl1000007** [comment]
יתאים למספר מקרים מצומצם מאוד.
בכל מקרה, אם משתמש כלשהו יבקש את זה, אפשר להריץ ידנית שאילתה ב-DB לא?
נניח על בסיס סה"כ פרסומי שאלה ותמיכות בשאלה
לדעתי אפשר לסגור
