### ISSUE TITLE
Show all the buttons, even for anonymous user

### ISSUE THREAD

**Issue by daonb** [hasadna/open-shot#79]
In a single question page, there are three buttons which are diaplyed on if the user is logged in and has permissions.  Better to show the buttons all the time and when the users clicks, tell him what to do to make his click count.

**Comment by amirnissim** [comment]
I'm on it

**Comment by amirnissim** [comment]
I am not sure it makes sense to show users neither
1. editor buttons like 'remove question'
2. nor candidate buttons like 'answer question'

I am only removing the 'disabled' state for 'flag question' button, which redirects to login anyways

https://github.com/amirnissim/okqa/commit/b3cb2c9d0ae407ded8e598c0852da514d5b4ff5c

**Comment by daonb** [comment]
@amirnissim can we close this?

**Comment by amirnissim** [comment]
yep
