### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by BoazChen** [hasadna/open-shot#82]
Not Found

The requested URL /search/ was not found on this server.

**Comment by BoazChen** [comment]
well, it doesn't. no error but is doen't find any word...

**Comment by lotan1** [comment]
the search eror is back 

Not Found
The requested URL /search/ was not found on this server.

http://localshot.org.il/search/?q=%D7%A9%D7%90%D7%9C%D7%94&place=%D7%90%D7%90-%D7%A2%D7%99%D7%A8-%D7%9C%D7%93%D7%95%D7%92%D7%9E%D7%90
